/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/RemoteManagement.framework/RemoteManagement
 */

@interface RemoteManagement.MKPrimaryKeyCert : _TtCs12_SwiftObject {
    void persistentRef;
}

@end
