/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/LinkMetadata.framework/LinkMetadata
 */

@interface LNLinkEnumerationValueType : LNValueType {
    NSString * _enumerationIdentifier;
}

@property (nonatomic, readonly, copy) NSString *enumerationIdentifier;

+ (id)objectClassesForCoding;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)enumerationIdentifier;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithEnumerationIdentifier:(id)arg1;
- (bool)isEqual:(id)arg1;
- (Class)objectClass;
- (id)typeIdentifierAsString;

@end
