/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKAccountWebServiceRequestPhysicalCardResponse : PKAccountWebServiceResponse {
    PKPhysicalCard * _physicalCard;
    unsigned long long  _shipmentQuoteMaximum;
    unsigned long long  _shipmentQuoteMinimum;
}

@property (nonatomic, readonly) PKPhysicalCard *physicalCard;
@property (nonatomic, readonly) unsigned long long shipmentQuoteMaximum;
@property (nonatomic, readonly) unsigned long long shipmentQuoteMinimum;

- (void).cxx_destruct;
- (id)initWithData:(id)arg1;
- (id)physicalCard;
- (unsigned long long)shipmentQuoteMaximum;
- (unsigned long long)shipmentQuoteMinimum;

@end
