/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKMerchantTokenDemoData : NSObject

+ (id)_generateTokensWithIdsUsing:(id)arg1;
+ (id)responseForPageNumber:(id)arg1;
+ (id)responseForSingleAMPMerchantToken;
+ (id)responseForSingleCashMerchantToken;
+ (id)responseForSingleMerchantToken;
+ (id)responseForSinglePage;

@end
