/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKNFCTagReaderSession : PKPaymentSession {
    <PKNFCTagReaderSessionDelegate> * _delegate;
}

@property (nonatomic) <PKNFCTagReaderSessionDelegate> *delegate;

- (void).cxx_destruct;
- (id)delegate;
- (void)endSession;
- (void)readNDEFMessageFromTag:(id)arg1 completion:(id /* block */)arg2;
- (void)setDelegate:(id)arg1;
- (void)startPolling;
- (void)stopPolling;

@end
