/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPeerPaymentTermsAcceptanceResponse : PKPeerPaymentWebServiceResponse {
    NSString * _termsIdentifier;
    NSURL * _termsURL;
}

@property (nonatomic, readonly, copy) NSString *termsIdentifier;
@property (nonatomic, readonly, copy) NSURL *termsURL;

- (void).cxx_destruct;
- (bool)hasTermsData;
- (id)initWithData:(id)arg1;
- (id)termsIdentifier;
- (id)termsURL;

@end
