/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPrivacyDeviceAssessmentRetrieveStateResponse : PKPaymentWebServiceResponse {
    NSNumber * _privacyUiState;
}

@property (nonatomic, retain) NSNumber *privacyUiState;

- (void).cxx_destruct;
- (id)initWithData:(id)arg1;
- (id)privacyUiState;
- (void)setPrivacyUiState:(id)arg1;

@end
