/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKSafariCardNotificationManager : NSObject {
    PKPaymentService * _paymentService;
}

- (void).cxx_destruct;
- (void)_eligibleToCheckWithCompletion:(id /* block */)arg1;
- (id)init;
- (void)userDidPerformAction:(long long)arg1 withCard:(id)arg2;

@end
