/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKWebServiceContext : NSObject <NSSecureCoding>

+ (id)contextWithArchive:(id)arg1;
+ (id)contextWithArchive:(id)arg1 error:(id*)arg2;
+ (bool)supportsSecureCoding;

- (void)archiveAtPath:(id)arg1;
- (bool)archiveAtPath:(id)arg1 error:(id*)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
