/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PegasusPersistence.framework/PegasusPersistence
 */

@interface _TtC18PegasusPersistenceP33_C0F182E319455B4338F1E058E352E18413KeyValueStore : _TtCs12_SwiftObject {
    void state;
}

@end
