/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreUtils.framework/CoreUtils
 */

@interface CURangingPeer : NSObject {
    NSData * _deviceAddress;
    NSData * _deviceIRK;
    NSString * _deviceModel;
}

@property (nonatomic, copy) NSData *deviceAddress;
@property (nonatomic, copy) NSData *deviceIRK;
@property (nonatomic, copy) NSString *deviceModel;

- (void).cxx_destruct;
- (id)description;
- (id)deviceAddress;
- (id)deviceIRK;
- (id)deviceModel;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)setDeviceAddress:(id)arg1;
- (void)setDeviceIRK:(id)arg1;
- (void)setDeviceModel:(id)arg1;

@end
