/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/IntelligencePlatform.framework/IntelligencePlatform
 */

@interface GDVUSocialGroup : NSObject {
    void inner;
}

@property (nonatomic, readonly) NSNumber *numberOfMomentNodes;
@property (nonatomic, readonly) NSArray *tags;

// GDVUSocialGroup (null)

- (void).cxx_destruct;
- (id)init;
- (id)initWithNumberOfMomentNodes:(id)arg1 tags:(id)arg2;
- (id)numberOfMomentNodes;
- (id)tags;

@end
