/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/IntelligencePlatform.framework/IntelligencePlatform
 */

@interface IntelligencePlatform.MentionGenerationInput : _TtCs12_SwiftObject <MLFeatureProvider> {
    void inputTokenIds;
}

@property (nonatomic, readonly) NSSet *featureNames;

// IntelligencePlatform.MentionGenerationInput (null)

- (id)featureNames;
- (id)featureValueForName:(id)arg1;

@end
