/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppAnalytics.framework/AppAnalytics
 */

@interface AARawEvent : NSObject {
    void name;
    void properties;
    void sessionGroup;
    void timestampGranularity;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithName:(id)arg1 properties:(id)arg2;
- (id)initWithName:(id)arg1 sessionGroup:(id)arg2 timestampGranularity:(long long)arg3 properties:(id)arg4;

@end
