/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/DeviceCheckInternal.framework/DeviceCheckInternal
 */

@interface DCXPCActivityController : NSObject

+ (id)sharedInstance;

- (id)_activityCriteriaWithFrequency:(double)arg1;
- (void)_performMetadataRefreshForActivity:(id)arg1;
- (void)_registerActivityWithInterval:(double)arg1;
- (void)start;
- (void)updateActivityScheduleWithAsset:(id)arg1;

@end
