/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGEntityStoreToFeatureStoreLockGuardedData : NSObject {
    SGMIFeatureStore * _sgmiFeatureStore;
}

- (void).cxx_destruct;
- (void)setSgmiFeatureStore:(id)arg1;
- (id)sgmiFeatureStore;

@end
