/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGMailPatterns : NSObject

+ (id)headerPattern;
+ (id)headerPattern:(id)arg1;
+ (id)headersPattern;
+ (id)messageSeparatorPattern;
+ (id)quotedRegionStartPattern;
+ (id)replyAttributionPattern;

@end
