/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGMISaliencyAnalyzer : NSObject

+ (id)analyzeSimpleMailMessage:(id)arg1 senderConnectionScore:(id)arg2 store:(id)arg3 logOrStageSaliency:(bool)arg4 commitSaliency:(bool)arg5 error:(id*)arg6;

@end
