/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/CoreSuggestionsInternals
 */

@interface SGPatternGlobalData : NSObject {
    NSArray * currentLanguages;
    int  globalLanguageVersion;
    SGPatternDataFile * patternData;
    NSDictionary * patternDict;
    NSHashTable * patternInstances;
    NSMutableSet * regexesImmuneToDeath;
    bool  useAllLanguages;
}

- (void).cxx_destruct;

@end
