/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SetupKit.framework/SetupKit
 */

@interface SKEventBasicConfigUpdated : SKEvent {
    NSDictionary * _basicConfig;
}

@property (nonatomic, readonly, copy) NSDictionary *basicConfig;

- (void).cxx_destruct;
- (id)basicConfig;
- (id)descriptionWithLevel:(int)arg1;
- (id)initWithBasicConfig:(id)arg1;

@end
