/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreMediaStream.framework/CoreMediaStream
 */

@interface MSTimerGate : NSObject {
    bool  _enabled;
}

@property (nonatomic) bool enabled;

- (void)disable;
- (void)enable;
- (bool)enabled;
- (id)init;
- (void)setEnabled:(bool)arg1;

@end
