/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ReminderKit.framework/ReminderKit
 */

@interface REMAuxiliaryChangeInfoFetchResult : NSObject {
    NSArray * _auxiliaryChangeInfos;
    NSMutableDictionary * _changeObjectForAuxiliaryChangeInfoMap;
    Class  _typedKlass;
}

@property (nonatomic, readonly) NSArray *auxiliaryChangeInfos;
@property (nonatomic, retain) NSMutableDictionary *changeObjectForAuxiliaryChangeInfoMap;
@property (nonatomic) Class typedKlass;

- (void).cxx_destruct;
- (id)auxiliaryChangeInfos;
- (id)changeObjectForAuxiliaryChangeInfo:(id)arg1;
- (id)changeObjectForAuxiliaryChangeInfoMap;
- (id)initWithAuxiliaryChangeInfoType:(Class)arg1;
- (void)setChangeObjectForAuxiliaryChangeInfoMap:(id)arg1;
- (void)setTypedKlass:(Class)arg1;
- (Class)typedKlass;

// REMAuxiliaryChangeInfoFetchResult (REMChangeTrackingInternalAccess)

+ (id)auxiliaryChangeInfoFetchResultOfType:(Class)arg1;

- (id)auxiliaryChangeInfoFromData:(id)arg1 withObjectID:(id)arg2 fromChangeObject:(id)arg3 error:(id*)arg4;
- (void)setAuxiliaryChangeInfos:(id)arg1;

@end
