/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ReminderKit.framework/ReminderKit
 */

@interface REMAccountTemplatesContext : NSObject {
    REMAccount * _account;
}

@property (nonatomic, retain) REMAccount *account;

- (void).cxx_destruct;
- (id)account;
- (id)fetchTemplatesWithError:(id*)arg1;
- (id)initWithAccount:(id)arg1;
- (void)setAccount:(id)arg1;

@end
