/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ReminderKit.framework/ReminderKit
 */

@interface REMExporting : NSObject

// REMExporting (ICSExport)

+ (id)_icsCalendarItemsFromReminders:(id)arg1 exportingOption:(long long)arg2;
+ (bool)_updateICSComponentWithReminder:(id)arg1 icsCalendarItem:(id)arg2;
+ (id)exportICSCalendarFromReminders:(id)arg1;
+ (id)exportICSCalendarFromReminders:(id)arg1 exportingOption:(long long)arg2;
+ (id)icsTodoFromReminder:(id)arg1;
+ (id)icsTodoFromReminder:(id)arg1 exportingOption:(long long)arg2;

@end
