/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/FileProvider.framework/FileProvider
 */

@interface FPNSURLBitVectorForBounce : NSObject {
    int  _bitCount;
    struct __CFBitVector { } * _vector;
}

@property (nonatomic, readonly) int bitCount;

- (int)bitCount;
- (id)findNextAvailableBounceNumber;
- (id)findNextAvailableBounceNumberFromIndex:(int)arg1;
- (bool)foundAllAvailableBounceNumbers;
- (id)init;
- (void)markBounceNumberAsFound:(id)arg1;

@end
