/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ResponseKit.framework/ResponseKit
 */

@interface RankingInfo : NSManagedObject

@property (nonatomic, copy) NSString *category;
@property (nonatomic) short inputMethod;
@property (nonatomic, copy) NSString *message;
@property (nonatomic, copy) NSString *rankedList;
@property (nonatomic, copy) NSString *recipientId;
@property (nonatomic, copy) NSString *response;
@property (nonatomic) short source;
@property (nonatomic, copy) NSDate *timestamp;

// RankingInfo (CoreDataProperties)

+ (id)fetchRequest;

@end
