/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
 */

@interface AVAssetInternal : NSObject {
    NSString * anchorChapterType;
    NSArray * availableCanonicalizedChapterLanguages;
    NSArray * availableChapterLanguages;
    NSArray * availableChapterLocales;
    NSArray * chapterGroupInfo;
    AVDispatchOnce * loadChapterInfoOnce;
    <AVLoggingIdentifier> * loggingIdentifier;
    AVWeakReference * weakReference;
}

@end
