/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
 */

@interface AVContentKeyResponse : NSObject {
    AVContentKeyResponseInternal * _keyResponse;
}

+ (id)contentKeyResponseWithAuthorizationTokenData:(id)arg1;
+ (id)contentKeyResponseWithClearKeyData:(id)arg1 initializationVector:(id)arg2;
+ (id)contentKeyResponseWithFairPlayStreamingKeyResponseData:(id)arg1;
+ (id)contentKeyResponseWithFairPlayStreamingKeyResponseData:(id)arg1 renewalDate:(id)arg2;

- (void)dealloc;
- (id)initWithKeySystem:(id)arg1;
- (id)keySystem;

@end
