/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
 */

@interface AVDateRangeMetadataGroupInternal : NSObject {
    NSString * classifyingLabel;
    NSString * cueingOptions;
    NSDate * discoveryTimestamp;
    NSDate * endDate;
    NSDictionary * extraFigProperties;
    NSArray * metadataItems;
    NSDate * modificationTimestamp;
    NSDate * startDate;
    NSString * uniqueID;
}

@end
