/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
 */

@interface AVExternalDeviceHID : NSObject {
    AVExternalDeviceHIDInternal * _externalDeviceHID;
}

@property (nonatomic, readonly) NSString *UUID;
@property (nonatomic) long long inputMode;
@property (nonatomic, readonly) NSString *screenID;

- (id)UUID;
- (id)_externalDevice;
- (id)_figEndpointHIDInputMode;
- (void)dealloc;
- (id)initWithExternalDeviceAndHIDDictionary:(id)arg1 hidDictionary:(id)arg2;
- (long long)inputMode;
- (id)screenID;
- (void)setInputMode:(long long)arg1;

@end
