/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
 */

@interface AVMutableMediaSelection : AVMediaSelection

- (bool)_isValidMediaSelectionOption:(id)arg1 forMediaSelectionGroup:(id)arg2;
- (id)_validatedGroupIdentifierKey:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)selectMediaOption:(id)arg1 inMediaSelectionGroup:(id)arg2;

@end
