/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
 */

@interface AVPlayerItemMetadataOutputInternal : NSObject {
    struct __CFDictionary { } * accumulatedMetadataGroups;
    NSObject<OS_dispatch_queue> * accumulationQueue;
    double  advanceInterval;
    AVWeakReferencingDelegateStorage * delegateStorage;
    NSObject<OS_dispatch_queue> * ivarAccessQueue;
    NSArray * metadataIdentifiers;
    AVWeakReference * weakReferenceToHost;
}

@end
