/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AccessibilityUIUtilities.framework/AccessibilityUIUtilities
 */

@interface AXDragEndpointClient : NSObject {
    NSXPCConnection * _connection;
}

+ (bool)isValidServiceName:(id)arg1;

- (void).cxx_destruct;
- (void)dealloc;
- (void)getDragEndpoint:(id /* block */)arg1;
- (id)initWithServiceName:(id)arg1;

@end
