/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/vCard.framework/vCard
 */

@interface CNVCardNameSerialization : NSObject

+ (id)compositeNameForCompanyWithComponents:(id)arg1;
+ (id)compositeNameForPersonWithComponents:(id)arg1;
+ (id)compositeNameWithComponents:(id)arg1;

@end
