/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/vCard.framework/vCard
 */

@interface CNVCardData : NSObject

+ (bool)isJPEGData:(id)arg1;
+ (id)stringFromUTF7Data:(id)arg1;

@end
