/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CarKey.framework/CarKey
 */

@interface CarKey.CarKeyRemoteControlSession : _TtCs12_SwiftObject {
    void delegate;
    void delegateCallbackQueue;
    void subscriptionRange;
}

@end
