/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BookLibraryCore.framework/BookLibraryCore
 */

@interface BLJaliscoServerInfo : NSManagedObject

@property (nonatomic, retain) NSString *databaseVersion;
@property (nonatomic) double lastPolledAt;
@property (nonatomic, retain) NSString *userUID;

- (id)initIntoManagedObjectContext:(id)arg1;

@end
