/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSDisplayLayoutMonitorConfiguration : NSObject {
    BSServiceConnectionEndpoint * _endpoint;
    bool  _needsUserInteractivePriority;
    id /* block */  _transitionHandler;
}

@property (nonatomic, readonly, copy) BSServiceConnectionEndpoint *endpoint;
@property (nonatomic) bool needsUserInteractivePriority;
@property (nonatomic, copy) id /* block */ transitionHandler;

+ (id)configurationForDefaultMainDisplayMonitor;
+ (id)configurationWithEndpoint:(id)arg1;

- (void).cxx_destruct;
- (id)_initWithEndpoint:(id)arg1;
- (id)endpoint;
- (id)init;
- (bool)needsUserInteractivePriority;
- (void)setNeedsUserInteractivePriority:(bool)arg1;
- (void)setTransitionHandler:(id /* block */)arg1;
- (id /* block */)transitionHandler;

@end
