/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GeoAnalytics.framework/GeoAnalytics
 */

@interface GEONanoInfo : NSObject

+ (id)sharedInfo;

- (id)deviceProductType;
- (id)deviceProductTypeIfAvailable;
- (id)deviceSystemBuildVersion;
- (id)deviceSystemBuildVersionIfAvailable;
- (id)deviceSystemVersion;
- (id)deviceSystemVersionIfAvailable;
- (id)hasPairedDevice;
- (id)hasPairedDeviceIfAvailable;

// GEONanoInfo (AnalyticsPipeline)

- (id)deviceOsVersionIfAvailable;

@end
