/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@interface C3DownloadChunkContext : NSObject {
    CKDMMCS * _MMCS;
    NSMutableDictionary * _signatureToMutableData;
}

@property (nonatomic) CKDMMCS *MMCS;
@property (nonatomic, retain) NSMutableDictionary *signatureToMutableData;

- (void).cxx_destruct;
- (id)MMCS;
- (id)initWithMMCS:(id)arg1;
- (void)setMMCS:(id)arg1;
- (void)setSignatureToMutableData:(id)arg1;
- (id)signatureToMutableData;

@end
