/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/ProtectedCloudStorage
 */

@interface PCSAccountManager : NSObject {
    NSString * _dsid;
}

@property (retain) NSString *dsid;

- (void).cxx_destruct;
- (unsigned long long)accountStatus;
- (id)dsid;
- (id)initWithDSID:(id)arg1;
- (void)setDsid:(id)arg1;

@end
