/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/WeatherAnalytics.framework/WeatherAnalytics
 */

@interface WeatherAnalytics.DynamicEndpoint : _TtCs12_SwiftObject <AAEndpointType> {
    void $__lazy_storage_$_contentEnvironment;
    void appConfigurationManager;
}

@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) NSString *sharedContainerIdentifier;
@property (nonatomic, readonly) NSURL *url;

- (id)name;
- (id)sharedContainerIdentifier;
- (id)url;

@end
