/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriReferenceResolution.framework/SiriReferenceResolution
 */

@interface SRRReferenceResolutionClient : NSObject {
    SRRReferenceResolutionClientInternal * _underlyingObject;
}

@property (readonly) SRRReferenceResolutionClientInternal *underlyingObject;

- (void).cxx_destruct;
- (void)collectSalientEntityStringsWithCompletion:(id /* block */)arg1;
- (void)collectSalientStringsWithCompletion:(id /* block */)arg1;
- (id)init;
- (id)underlyingObject;

@end
