/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriAnalytics.framework/SiriAnalytics
 */

@interface SiriAnalytics.SiriAnalyticsMessageStaging : NSObject {
    void stagingActor;
}

- (void).cxx_destruct;
- (void)bootstrapAndPrune;
- (id)init;

@end
