/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/KnowledgeGraphKit.framework/KnowledgeGraphKit
 */

@interface MALearningStreamResult : NSObject {
    _TtC17KnowledgeGraphKit29MAWrapperLearningStreamResult * _underlyingObject;
}

@property (nonatomic, readonly) double confidence;
@property (nonatomic, readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *detectedClass;

- (void).cxx_destruct;
- (double)confidence;
- (id)description;
- (id)detectedClass;
- (id)initWithWrapperLearningStreamResult:(id)arg1;

@end
