/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MetalSerializer.framework/MetalSerializer
 */

@interface MTLDeserializerBlitDecoder : NSObject <MTLDeserializerDecoder> {
    <MTLBlitCommandEncoderSPI> * blitEncoder;
    _MTLDeserializer * deserializer;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly) unsigned char type;

- (void)dealloc;
- (void)decodeBlitUpdateFence:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeBlitWaitForFence:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeCopyFromBufferToBuffer:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeCopyFromBufferToTexture:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeCopyFromTextureToBuffer:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeCopyFromTextureToTexture:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeCopyFromTextureToTextureWithNumSliceLevel:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeCopyFromTextureToTextureWithOptions:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeFillBuffer:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeGenerateMipmaps:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeOptimize:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeOptimizeImage:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeSynchronizeResource:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeSynchronizeTextureImage:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2;
- (void)decodeWithHeader:(struct { unsigned int x1; unsigned char x2; unsigned char x3; unsigned char x4; }*)arg1 withIterator:(id)arg2;
- (void)fault;
- (id)getBufferForReferenceNonNull:(unsigned int)arg1;
- (id)getTextureForReferenceNonNull:(unsigned int)arg1;
- (id)initWithDeserializer:(id)arg1 commandBuffer:(id)arg2;
- (void)readCommand:(struct { unsigned int x1; unsigned int x2; }*)arg1 withIterator:(id)arg2 expectedSize:(unsigned long long)arg3 into:(void*)arg4;
- (unsigned char)type;

@end
