/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSKeyValueDidWillStats : NSObject {
    long long  _count;
    struct { 
        bool hasBecomeReentrant; 
        bool hasExcessiveDids; 
        bool hasWillDidThreadMismatch; 
    }  _detectedIssues;
    bool  _hasDecreased;
    NSThread * _originalThread;
}

- (void)_recordThread;
- (void)dealloc;

@end
