/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSUndoBeginMark : _NSUndoObject {
    id  _groupIdentifier;
    bool  _isDiscardable;
}

- (void)dealloc;
- (id)description;
- (id)groupIdentifier;
- (bool)isBeginMark;
- (bool)isDiscardable;
- (void)setDiscardable:(bool)arg1;
- (void)setGroupIdentifier:(id)arg1;

@end
