/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSUnitConcentrationMass : NSDimension <NSSecureCoding>

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation

+ (id)baseUnit;
+ (id)gramsPerLiter;
+ (id)icuType;
+ (void)initialize;
+ (id)milligramsPerDeciliter;
+ (id)millimolesPerLiterWithGramsPerMole:(double)arg1;
+ (bool)supportsRegionalPreference;

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/HealthKit.framework/HealthKit

// NSUnitConcentrationMass (HKUnit)

- (id)hk_equivalentBaseUnit;

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ContentKit.framework/ContentKit

// NSUnitConcentrationMass (WFAdditionalUnits)

+ (id)wf_microgramsPerCubicMeter;

@end
