/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TimeSync.framework/TimeSync
 */

@interface TSXAnonymousClient : NSObject {
    bool  _invalidated;
    NSXPCConnection * _serverConnection;
}

@property (readonly) NSXPCConnection *serverConnection;

+ (id)clientProtocol;
+ (id)serverProtocol;

- (void).cxx_destruct;
- (void)dealloc;
- (id)exportedObject;
- (id)initWithEndpoint:(id)arg1;
- (void)interruptedConnection;
- (void)invalidatedConnection;
- (id)serverConnection;

@end
