/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/RenderBox.framework/RenderBox
 */

@interface RBDecodedFontMetadata : NSObject {
    struct cf_ptr<const __CFDictionary *> { 
        struct __CFDictionary {} *_p; 
    }  _glyph_map;
    struct cf_ptr<const __CFString *> { 
        struct __CFString {} *_p; 
    }  _uid;
}

- (id).cxx_construct;
- (void).cxx_destruct;

@end
