/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/PDFKit.framework/PDFKit
 */

@interface PDFTextWidgetTextView : UITextView

- (id)accessibilityLabel;
- (id)accessibilityParent;
- (id)accessibilityTitleUIElement;
- (void)handleBackTab;
- (void)handleTab;
- (void)insertTextSuggestion:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)keyCommands;

@end
