/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SystemStatusServer.framework/SystemStatusServer
 */

@interface STExecutableIdentityResolver : NSObject <STExecutableIdentityResolving> {
    STReferenceCountedCache * _cache;
}

+ (id)responsibleIdentityForAuditToken:(struct { unsigned int x1[8]; })arg1;

- (void).cxx_destruct;
- (id)beginBatchResolutionSession;
- (id)init;
- (id)resolvedIdentityForIdentity:(id)arg1;

@end
