/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreTransferable.framework/CoreTransferable
 */

@interface CTAttributedStringConstant : NSObject

+ (id)documentType;
+ (id)html;
+ (id)rtf;
+ (id)rtfd;

@end
