/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVFCapture.framework/AVFCapture
 */

@interface AVCapturePhotoInitiationSettingsInternal : NSObject {
    long long  HDRMode;
    bool  autoStillImageStabilizationEnabled;
    bool  burstQualityCaptureEnabled;
    long long  flashMode;
    unsigned long long  timestamp;
    long long  uniqueID;
}

@end
