/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriUtilities.framework/SiriUtilities
 */

@interface SiriUtilities.SiriEnvironment : _TtCs12_SwiftObject {
    void children;
    void cycleDetector;
    void lock;
    void parent;
    void providers;
    void scope;
}

@end
