/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MailServices.framework/MailServices
 */

@interface MSOpenComposeDelegateRequest : MSXPCService

- (void)checkInComposeWithIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (id)init;

@end
