/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MetricMeasurement.framework/MetricMeasurement
 */

@interface MXMUnitMemory : NSDimension

+ (id)baseUnit;
+ (id)bits;
+ (id)bytes;
+ (id)nibbles;

// MXMUnitMemory (Exa)

+ (id)exabits;
+ (id)exabytes;

// MXMUnitMemory (Exbi)

+ (id)exbibits;
+ (id)exbibytes;

// MXMUnitMemory (Gibi)

+ (id)gibibits;
+ (id)gibibytes;

// MXMUnitMemory (Giga)

+ (id)gigabits;
+ (id)gigabytes;

// MXMUnitMemory (Kibi)

+ (id)kibibits;
+ (id)kibibytes;

// MXMUnitMemory (Kilo)

+ (id)kilobits;
+ (id)kilobytes;

// MXMUnitMemory (Mebi)

+ (id)mebibits;
+ (id)mebibytes;

// MXMUnitMemory (Mega)

+ (id)megabits;
+ (id)megabytes;

// MXMUnitMemory (Pebi)

+ (id)pebibits;
+ (id)pebibytes;

// MXMUnitMemory (Peta)

+ (id)petabits;
+ (id)petabytes;

// MXMUnitMemory (Tebi)

+ (id)tebibits;
+ (id)tebibytes;

// MXMUnitMemory (Tera)

+ (id)terabits;
+ (id)terabytes;

@end
