/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NotesSupport.framework/NotesSupport
 */

@interface ICCFTypeWrapper : NSObject {
    void * _cfTypeRef;
}

@property (nonatomic) void*cfTypeRef;

- (void*)cfTypeRef;
- (void)dealloc;
- (unsigned long long)hash;
- (id)initWithCFTypeRef:(void*)arg1;
- (bool)isEqual:(id)arg1;
- (void*)ref;
- (void)setCfTypeRef:(void*)arg1;

@end
