/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreAutoLayout.framework/CoreAutoLayout
 */

@interface _NSLayoutRuleNode : NSObject {
    <_NSLayoutRuleNodeParent> * _parentNode;
    <NSLayoutRule> * _representedRule;
}

@property <_NSLayoutRuleNodeParent> *parentNode;
@property (copy) <NSLayoutRule> *representedRule;

- (void)dealloc;
- (id)description;
- (id)initWithRule:(id)arg1;
- (id)parentNode;
- (id)representedRule;
- (void)setParentNode:(id)arg1;
- (void)setRepresentedRule:(id)arg1;

@end
