/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNCIContext : NSObject {
    CIContext * _ciContext;
    VNCIContextsHandler * _handler;
}

- (void).cxx_destruct;

@end
