/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNFaceAnalyzerMultiDetectorFPrev3_1FArev1_3_MD3 : VNFaceAnalyzerMultiDetector

+ (id)espressoModelFileNameForConfigurationOptions:(id)arg1;
+ (const void*)modelVersionForOptions:(id)arg1;

- (bool)_isFaceprintJunk:(struct shared_ptr<vision::mod::ImageDescriptorBufferAbstract> { struct ImageDescriptorBufferAbstract {} *x1; struct __shared_weak_count {} *x2; })arg1;

@end
