/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ProactiveSupportStubs.framework/ProactiveSupportStubs
 */

@interface _PASDeviceStateStub : _PASDeviceState

+ (void)setClassCLocked:(bool)arg1;
+ (void)setCurrentOsBuild:(id)arg1;
+ (void)setDeviceFormattedForProtection:(bool)arg1;
+ (void)setLockState:(int)arg1;
+ (void)setLockStateAKS:(int)arg1;
+ (void)startMockingSystem;
+ (void)stopMockingSystem;

@end
