/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
 */

@interface TRIMobileAssetUtil : NSObject

+ (void)_setAllAssetsToAudience:(id)arg1 siriAudience:(id)arg2 assetURL:(id)arg3 siriAssetURL:(id)arg4;
+ (id)allTrialAssetTypes;
+ (void)configureMobileAssetForTrialEnvironment:(long long)arg1;
+ (id)siriTrialAssetTypes;

@end
