/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
 */

@interface TRIRemoteAssetDecrypter : NSObject

+ (bool)decryptAssetWithURL:(id)arg1 destinationFilename:(id)arg2 namespaceName:(id)arg3 error:(id*)arg4;

@end
