/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/IDS.framework/IDS
 */

@interface IDSTransportLog : NSObject

+ (id)IDSConnection;
+ (id)IDSDataChannels;
+ (id)IDSDeviceConnection;
+ (id)IDSLocalSetup;
+ (id)IDSReportSpam;
+ (id)IDSService;
+ (id)NRPairing;
+ (id)QRAllocator;

@end
