/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/WeatherDaemon.framework/WeatherDaemon
 */

@interface WeatherDaemon.NoCacheWeatherDataManager : _TtCs12_SwiftObject {
    void interpolator;
    void lastFetched;
    void lock;
    void service;
}

@end
