/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriTasks.framework/SiriTasks
 */

@interface STShowChannelRequest : AFSiriRequest {
    STMediaChannel * _channel;
}

@property (nonatomic, readonly) STMediaChannel *channel;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_initWithChannel:(id)arg1;
- (id)channel;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
