/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/ActivityKit.framework/ActivityKit
 */

@interface ActivityKit.ActivityPushTokenManager : _TtCs12_SwiftObject {
    void _lock_pushTokenByActivityId;
    void lock;
    void pushTokenPublisherByActivityId;
    void pushTokenStore;
    void subscriptions;
}

@end
