/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NeuralNetworks.framework/NeuralNetworks
 */

@interface _TtCC14NeuralNetworks31LazyTensorFunctionExecutorCacheP33_06A449572F5D7FD3153D46A4B2EF285410CacheValue : _TtCs12_SwiftObject {
    void key;
    void next;
    void previous;
    void value;
}

@end
