/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NeuralNetworks.framework/NeuralNetworks
 */

@interface _TtC14NeuralNetworksP33_9B5544FBA68FCA465842580971E7569418ParametrizedLayers : _TtCs12_SwiftObject

@end
