/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NeuralNetworks.framework/NeuralNetworks
 */

@interface NeuralNetworks.MPSAllocator : _TtCs12_SwiftObject {
    void $__lazy_storage_$_highWatermarkLimit;
    void $__lazy_storage_$_lowWatermarkLimit;
    void heapPool;
    void sharedDevice;
}

@end
