/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NeuralNetworks.framework/NeuralNetworks
 */

@interface SNNMILOperationEnumerator : NSEnumerator {
    int  _currentIndex;
    SNNMILFunction * _function;
}

@property (nonatomic) SNNMILFunction *function;

- (void).cxx_destruct;
- (id)function;
- (id)initWithFunction:(id)arg1;
- (id)nextObject;
- (void)setFunction:(id)arg1;

@end
