/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSLRUCacheItem : AMSDoubleLinkedListNode {
    <NSCopying> * _key;
}

@property (nonatomic) <NSCopying> *key;

- (void).cxx_destruct;
- (id)initWithKey:(id)arg1 object:(id)arg2;
- (id)key;
- (void)setKey:(id)arg1;

@end
