/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSMemoryPressure : NSObject

+ (id)_memoryPressureStatusForMemoryPressure:(unsigned int)arg1;
+ (void)initialize;
+ (id)lastKnownStatus;
+ (id)observable;
+ (void)subscribe:(id)arg1;
+ (void)unsubscribe:(id)arg1;

@end
