/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSStorageDataMigrator : NSObject

+ (void)_migrateDeviceOfferEligibilityWithDatabase:(id)arg1;
+ (void)_migrateSharedStoreReviewWithDatabase:(id)arg1;
+ (void)migrateStorageToDefaultsForNonAMSInternal:(id)arg1;

@end
