/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSUnitTests : NSObject

+ (id)_encryptionKeys;
+ (void)_sync:(id /* block */)arg1;
+ (id)encryptionKeyForDataProtectionClass:(unsigned long long)arg1;
+ (bool)isRunningUnitTests;
+ (void)setEncryptionKey:(id)arg1 forDataProtectionClass:(unsigned long long)arg2;

@end
