/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSVersionComparator : NSObject

+ (id)_sanitizedVersionStringForVersionString:(id)arg1;
+ (bool)isVersionSupported:(id)arg1 requiredVersion:(id)arg2;

@end
