/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SecurityFoundation.framework/SecurityFoundation
 */

@interface SFSymmetricKeyAttributes_Ivars : NSObject {
    NSString * keyDomain;
    _SFKeySpecifier * keySpecifier;
    NSString * localizedDescription;
    NSString * localizedLabel;
}

- (void).cxx_destruct;

@end
