/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@interface AADeviceListResponse : AAResponse {
    NSArray * _devices;
}

@property (nonatomic, readonly) NSArray *devices;

- (void).cxx_destruct;
- (id)devices;
- (id)initWithHTTPResponse:(id)arg1 data:(id)arg2;

@end
