/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKConcreteNetworkPrimitives : NSObject <CRKNetworkPrimitives>

+ (id)makePathMonitorForInterfaceType:(int)arg1;

- (id)ethernetNetworkPathMonitor;
- (id)wifiNetworkPathMonitor;

@end
