/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKConcreteFeatureFlags : NSObject <CRKFeatureFlags>

@property (getter=isASMUserCachingEnabled, nonatomic, readonly) bool ASMUserCachingEnabled;
@property (getter=isDataSeparationEnabled, nonatomic, readonly) bool dataSeparationEnabled;

- (bool)isASMUserCachingEnabled;
- (bool)isDataSeparationEnabled;

@end
