/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKLocalDeviceIPAddresses : NSObject {
    NSSet * _IPAddresses;
}

@property (nonatomic, readonly, copy) NSSet *IPAddresses;

+ (id)makeIPAddresses;

- (void).cxx_destruct;
- (id)IPAddresses;
- (bool)containsIPAddress:(id)arg1;
- (id)init;

@end
