/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKRestrictionsObserver : NSObject

+ (void)addRestrictionsObserver:(id)arg1;
+ (void)removeRestrictionsObserver:(id)arg1;

@end
