/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKTrustEvaluationPolicies : NSObject {
    NSArray * _policyRefs;
}

@property (nonatomic, readonly, copy) NSArray *policyRefs;

+ (id)defaultPolicicesForServerEvaluation;
+ (id)defaultPoliciesForClientEvaluation;

- (void).cxx_destruct;
- (id)init;
- (id)initWithPolicyRefs:(id)arg1;
- (id)policyRefs;

@end
