/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/WeatherCore.framework/WeatherCore
 */

@interface WeatherCore.StubPPTWeatherDataManager : _TtCs12_SwiftObject {
    void _cachedAirQualityScale;
    void _cachedWeather;
    void encoder;
    void listeningPort;
    void mockServer;
    void pingResponse;
    void queryString;
    void stubNextHourPrecipitation;
    void weatherDataBuilder;
}

@end
