/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Photos.framework/Photos
 */

@interface PHAssetCrashRecoverySupport : NSObject <PLXPCUserInfo> {
    PLLibraryServicesManager * _libraryServicesManager;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_commitRequest:(id)arg1 reply:(id /* block */)arg2;
- (bool)_isCrashRecoveryFilename:(id)arg1;
- (bool)_isSafeToRecoverAfterCrashForCrashRecoveryFileURL:(id)arg1;
- (id)initWithLibraryServicesManager:(id)arg1;
- (id)libraryServicesManager;
- (id)persistentStoreCoordinator;
- (void)recoverFromCrashIfNeeded;

@end
