/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Photos.framework/Photos
 */

@interface PHAssetCrashRecoveryUnarchiver : NSKeyedUnarchiver <PLXPCCoder> {
    <NSObject> * _userInfo;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (retain) <NSObject> *userInfo;

- (void).cxx_destruct;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;

@end
