/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SoundAnalysis.framework/SoundAnalysis
 */

@interface _TtCV13SoundAnalysis1X11Environment : _TtCs12_SwiftObject {
    void builtInHighPowerMicPublisher;
    void builtInHighPowerMicSubject;
}

@end
