/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SoundAnalysis.framework/SoundAnalysis
 */

@interface SNDetectorHeadConfiguration : NSObject {
    NSString * _detectorIdentifier;
    <SNProcessorCreating> * _featureExtractorConfiguration;
    <SNMLModel> * _model;
    NSString * _outputLabel;
    NSPredicate * _resultsPredicate;
    long long  _resultsPredicateLeakCount;
    double  _sampleRate;
    unsigned int  _stepSizeFrames;
    unsigned int  _windowLengthFrames;
}

- (void).cxx_destruct;

@end
