/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SoundAnalysis.framework/SoundAnalysis
 */

@interface SoundAnalysis.XPCProxyXPCHost : NSObject <SoundAnalysis.XPCProxyXPCProtocol> {
    void hosted;
}

- (void).cxx_destruct;
- (id)init;
- (void)xpcSendMessageWithData:(id)arg1 proxy:(id)arg2 completionHandler:(id /* block */)arg3;

@end
