/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriPrivateLearningAnalytics.framework/SiriPrivateLearningAnalytics
 */

@interface SiriPrivateLearningAnalytics.BiomeFilterUserCallAfterHangupSiriCall : _TtCs12_SwiftObject {
    void lastSiriCallTimestamp;
    void lastUserHangupTimestamp;
    void userCallAfterHangupMaxInterval;
    void userHangupAfterSiriCallMaxInterval;
}

@end
