/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AuthKit.framework/AuthKit
 */

@interface AKAutoBugCapture : NSObject

+ (bool)shouldCapturePromptBugForContext:(id)arg1;
+ (void)triggerAutoBugCaptureWithSubType:(id)arg1 andBundleID:(id)arg2 userInfo:(id)arg3;
+ (id)userInfoFromAccount:(id)arg1;
+ (id)userInfoFromContext:(id)arg1;

@end
