/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/Sleep.framework/Sleep
 */

@interface HKSPHealthStoreProvider : NSObject {
    HKHealthStore * _healthStore;
    HKSleepHealthStore * _sleepHealthStore;
}

@property (nonatomic, readonly) HKHealthStore *healthStore;
@property (nonatomic, readonly) HKSleepHealthStore *sleepHealthStore;

+ (id)_initializedLocalDeviceHealthStore;

- (void).cxx_destruct;
- (id)healthStore;
- (id)initWithLocalDeviceHealthStore;
- (id)initWithSleepHealthStore:(id)arg1 healthStore:(id)arg2;
- (id)sleepHealthStore;

@end
