/* Generated by RuntimeBrowser.
 */

@protocol MTSXPCServerInterface <MTSDevicePairingServerInterface, MTSDeviceSetupServerInterface, MTSSystemCommissionerPairingServerInterface, MTSAuthorizationServerInterface>

@end
