/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CallKit.framework/CallKit
 */

@interface CXChannelAction : CXAction <CXCopying, CXSecureCoding> {
    NSUUID * _channelUUID;
}

@property (nonatomic, readonly, copy) NSUUID *channelUUID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)channelUUID;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)customDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithChannelUUID:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)sanitizedCopyWithZone:(struct _NSZone { }*)arg1;
- (void)updateSanitizedCopy:(id)arg1 withZone:(struct _NSZone { }*)arg2;

// CXChannelAction (Internal)

+ (id)unarchivedObjectClasses;
+ (id)unarchivedObjectFromData:(id)arg1 error:(id*)arg2;

- (id)archivedDataWithError:(id*)arg1;

@end
