/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CalendarDaemon.framework/CalendarDaemon
 */

@interface CADStatsCalendars : CADStatCollector {
    NSMutableArray * _calendarInfos;
    CADStatCollectionContext * _context;
}

+ (id)eventName;

- (void).cxx_destruct;
- (bool)calendarUsesAuthentication:(void*)arg1;
- (id)eventDictionaries;
- (void)prepareWithContext:(id)arg1;
- (void)processCalendars:(id)arg1 inStore:(void*)arg2;
- (bool)wantsCalendars;

@end
