/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
 */

@interface TUICFQueryResult : NSObject {
    bool  _allowCallForDestinationID;
    bool  _fromBlockList;
}

@property (nonatomic) bool allowCallForDestinationID;
@property (getter=isFromBlockList, nonatomic) bool fromBlockList;

- (bool)allowCallForDestinationID;
- (id)description;
- (bool)isFromBlockList;
- (void)setAllowCallForDestinationID:(bool)arg1;
- (void)setFromBlockList:(bool)arg1;

@end
