/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/AVConference
 */

@interface SIPClientDataDictionary : NSObject {
    NSMutableDictionary * allCalls;
}

- (id)copyObjectForKey:(id)arg1 p2pID:(unsigned int)arg2;
- (void)dealloc;
- (id)init;
- (void)setObject:(id)arg1 forKey:(id)arg2 forP2PID:(unsigned int)arg3;

@end
