/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/DialogEngine.framework/DialogEngine
 */

@interface DESizeWriter : NSObject <DEWriter> {
    unsigned long long  _size;
}

@property (nonatomic) unsigned long long size;

- (void)close;
- (id)init;
- (void)setSize:(unsigned long long)arg1;
- (unsigned long long)size;
- (void)writeData:(id)arg1;

@end
