/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/JetUI.framework/JetUI
 */

@interface JetUI.LayoutViewPlaceholder : _TtCs12_SwiftObject {
    void frame;
    void hasContent;
    void isHidden;
    void measureLogic;
}

@end
