/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TrialProto.framework/TrialProto
 */

@interface TRIPBMixin : TRIPBMessage

@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *root;

+ (id)descriptor;

@end
