/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BiomeFoundation.framework/BiomeFoundation
 */

@interface BMStoreDirectory : NSObject

// BMStoreDirectory (BiomeInternalOnly)

+ (id)artifacts;
+ (id)bookmarks;
+ (id)client;
+ (id)compute;
+ (id)databases;
+ (id)flexibleStorage;
+ (id)localDevice;
+ (id)lock;
+ (id)metadata;
+ (id)nonwaking;
+ (id)persistent;
+ (id)private;
+ (id)public;
+ (id)remoteDevices;
+ (id)restricted;
+ (id)server;
+ (id)sessions;
+ (id)sharedSync;
+ (id)streams;
+ (id)subscriptions;
+ (id)sync;
+ (id)tmp;
+ (id)tombstones;

// BMStoreDirectory (TestingSupport)

+ (void)setBasePathForTestingWithPath:(id)arg1;
+ (void)unsetBasePathForTesting;

@end
