/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TextComposer.framework/TextComposer
 */

@interface TCPhraseCollector : NSObject {
    NSXPCConnection * _connection;
    bool  _valid;
}

// TCPhraseCollector (null)

+ (id)sharedInstance;

- (void).cxx_destruct;
- (bool)_initConnection;
- (void)collectSentence:(id)arg1 language:(id)arg2 phraseRanges:(id)arg3;
- (id)connection;
- (id)init;
- (bool)isValid;
- (void)setValid:(bool)arg1;

@end
