/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SignpostSupport.framework/SignpostSupport
 */

@interface SignpostAnimationArrayWeakWrapper : NSObject {
    SignpostAnimationInterval * _animationInterval;
}

@property (nonatomic, readonly) SignpostAnimationInterval *animationInterval;

- (void).cxx_destruct;
- (id)animationInterval;
- (id)initWithAnimationInterval:(id)arg1;

@end
