/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

@interface ICSStatusValue : ICSPredefinedValue {
    NSString * _statusString;
}

@property (retain) NSString *statusString;

+ (id)statusTypeFromCode:(int)arg1;
+ (id)statusTypeFromCode:(int)arg1 statusString:(id)arg2;

- (void).cxx_destruct;
- (Class)classForCoder;
- (void)setStatusString:(id)arg1;
- (id)statusString;

// ICSStatusValue (ICSWriter)

- (void)_ICSStringWithOptions:(unsigned long long)arg1 appendingToString:(id)arg2;

// ICSStatusValue (iCalendarImport)

+ (id)statusValueFromICSString:(id)arg1;

@end
