/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/DebugHierarchyFoundation.framework/DebugHierarchyFoundation
 */

@interface DebugHierarchyFormatSpecifier : NSObject {
    NSString * _format;
    NSString * _label;
}

@property (retain) NSString *format;
@property (retain) NSString *label;

+ (id)specifierWithFormat:(id)arg1 label:(id)arg2;

- (void).cxx_destruct;
- (id)format;
- (id)initWithFormat:(id)arg1 label:(id)arg2;
- (id)label;
- (void)setFormat:(id)arg1;
- (void)setLabel:(id)arg1;

@end
