/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/IntentsCore.framework/IntentsCore
 */

@interface _INCOptionalLocalExtension : NSObject <INCLocalExtending>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *localExtensionIdentifier;
@property (readonly) Class superclass;

- (id)handlerForIntent:(id)arg1;
- (id)localExtensionIdentifier;

@end
