/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ProactiveSupport.framework/ProactiveSupport
 */

@interface _PASSqliteCollectionsConstraintPlanInfo : NSObject {
    double  _estimatedCost;
    double  _estimatedRows;
    bool  _omit;
    bool  _unique;
}

- (id)initWithEstimatedRows:(double)arg1 estimatedCost:(double)arg2 unique:(bool)arg3 omit:(bool)arg4;

@end
