/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ShazamInsights.framework/ShazamInsights
 */

@interface SHFileChecksum : NSObject

+ (id)checksumDataForFile:(id)arg1 withError:(id*)arg2;
+ (id)checksumForFile:(id)arg1 withError:(id*)arg2;

@end
