/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ShazamInsights.framework/ShazamInsights
 */

@interface SHSQLiteClusterImporter : NSObject <SHClusterImporter>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (bool)loadDataFromFileInfo:(id)arg1 withMetadata:(id)arg2 toDestinationURL:(id)arg3 error:(id*)arg4;

@end
