/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/RemoteManagementStore.framework/RemoteManagementStore
 */

@interface RMStoreXPCConnection : NSObject {
    NSXPCConnection * _connection;
}

@property (readonly) NSXPCConnection *connection;

+ (id)storeXPCConnection:(id)arg1;

- (void).cxx_destruct;
- (id)connection;
- (void)dealloc;
- (id)initWithXPCConnection:(id)arg1;

@end
