/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFRefreshStatusResultObject : CATTaskResultObject {
    NSNumber * _numberOfUpdates;
}

@property (nonatomic, copy) NSNumber *numberOfUpdates;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)numberOfUpdates;
- (void)setNumberOfUpdates:(id)arg1;

@end
