/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BiomePubSub.framework/BiomePubSub
 */

@interface BPSMerge : BMBookmarkablePublisher {
    <BPSPublisher> * _a;
    <BPSPublisher> * _b;
    bool  _nextIsB;
}

@property (nonatomic, readonly) <BPSPublisher> *a;
@property (nonatomic, readonly) <BPSPublisher> *b;
@property (nonatomic) bool nextIsB;

+ (id)new;

- (void).cxx_destruct;
- (id)a;
- (void)applyBookmark:(id)arg1;
- (id)b;
- (id)bookmark;
- (id)init;
- (id)initWithA:(id)arg1 b:(id)arg2;
- (id)nextEvent;
- (bool)nextIsB;
- (void)reset;
- (void)setNextIsB:(bool)arg1;
- (void)subscribe:(id)arg1;
- (id)upstreamPublishers;
- (id)validateBookmark:(id)arg1;

// BPSMerge (BMBookmarkOperators)

+ (id)publisherWithPublisher:(id)arg1 upstreams:(id)arg2 bookmarkState:(id)arg3;

- (id)bookmarkableUpstreams;
- (bool)canStoreInternalStateInBookmark;

@end
