/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/EmbeddedAcousticRecognition.framework/EmbeddedAcousticRecognition
 */

@interface _EARSpeakerCodeReader : NSObject

- (void)getTrainingSpeakerCode:(id*)arg1 inferenceSpeakerCode:(id*)arg2 accumulatedGradient:(id*)arg3 nnetVersion:(id*)arg4 numFrames:(id*)arg5 trainingOffset:(id*)arg6 recognitionOffset:(id*)arg7 language:(id)arg8;

@end
