/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MTLSimDriver.framework/MTLSimDriver
 */

@interface MTLSimBuffer : MTLSimResource <MTLBufferSPI, MTLSerializerBuffer, MTLSerializerResource> {
    unsigned int  _bufferRef;
    void * _content;
    id /* block */  _deallocator;
    unsigned long long  _gpuAddress;
    struct __IOSurface { } * _iosurface;
    unsigned long long  _length;
    void * _pointer;
}

@property (readonly) unsigned long long allocatedSize;
@property (readonly) unsigned long long allocationID;
@property (readonly) unsigned int bufferRef;
@property (readonly) unsigned long long cpuCacheMode;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) <MTLDevice> *device;
@property (readonly) unsigned long long gpuAddress;
@property (readonly) unsigned long long hash;
@property (readonly) unsigned long long hazardTrackingMode;
@property (readonly) <MTLHeap> *heap;
@property (readonly) unsigned long long heapOffset;
@property (readonly) struct __IOSurface { }*iosurface;
@property (copy) NSString *label;
@property (readonly) unsigned long long length;
@property (nonatomic) unsigned long long parentGPUAddress;
@property (nonatomic) unsigned long long parentGPUSize;
@property (readonly) unsigned long long protectionOptions;
@property (nonatomic, readonly) unsigned long long resourceIndex;
@property (readonly) unsigned long long resourceOptions;
@property int responsibleProcess;
@property (readonly) unsigned int serializerResourceRef;
@property (readonly) unsigned long long storageMode;
@property (readonly) Class superclass;
@property (readonly) unsigned long long unfilteredResourceOptions;

- (struct __IOSurface { }*)_aneIOSurface;
- (void)addDebugMarker:(id)arg1 range:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;
- (unsigned int)bufferRef;
- (void*)contents;
- (void)dealloc;
- (id)description;
- (void)didModifyRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (id)formattedDescription:(unsigned long long)arg1;
- (unsigned long long)gpuAddress;
- (id)initWithDevice:(id)arg1 bufferRef:(unsigned int)arg2 content:(void*)arg3 pointer:(void*)arg4 length:(unsigned long long)arg5 options:(unsigned long long)arg6 heap:(id)arg7 deallocator:(id /* block */)arg8;
- (struct __IOSurface { }*)iosurface;
- (unsigned long long)length;
- (id)newLinearTextureWithDescriptor:(id)arg1 offset:(unsigned long long)arg2 bytesPerRow:(unsigned long long)arg3 bytesPerImage:(unsigned long long)arg4;
- (id)newRemoteBufferViewForDevice:(id)arg1;
- (id)newTextureWithDescriptor:(id)arg1 offset:(unsigned long long)arg2 bytesPerRow:(unsigned long long)arg3;
- (void)removeAllDebugMarkers;

@end
