/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKEventDetailURLCell : EKEventDetailCell <UITextViewDelegate> {
    UILabel * _URLTitleView;
    UITextView * _URLView;
    int  _lastLayoutPosition;
    SGSuggestedEventLaunchInfo * _launchInfo;
    NSURL * _url;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/EventKitUI.framework/EventKitUI

+ (Class)_SGSuggestionsServiceClass;

- (void).cxx_destruct;
- (id)_URLTitleView;
- (id)_URLView;
- (void)_layoutForWidth:(double)arg1 position:(int)arg2;
- (id)initWithEvent:(id)arg1 launchInfo:(id)arg2 editable:(bool)arg3 style:(long long)arg4;
- (id)initWithEvent:(id)arg1 url:(id)arg2 editable:(bool)arg3 style:(long long)arg4;
- (void)layoutForWidth:(double)arg1 position:(int)arg2;
- (void)layoutSubviews;
- (id)textView:(id)arg1 primaryActionForTextItem:(id)arg2 defaultAction:(id)arg3;
- (bool)update;
- (bool)updateLink;
- (void)updateLinkWithLaunchInfo;
- (void)updateLinkWithURL;
- (void)updateWithURL:(id)arg1 launchInfo:(id)arg2;

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/AccessibilityBundles/EventKitUIFramework.axbundle/EventKitUIFramework

- (id)accessibilityElements;
- (bool)isAccessibilityElement;

// EKEventDetailURLCell (SafeCategory)

+ (Class)safeCategoryBaseClass;

@end
