/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKUIInviteesViewOriginalConflictCell : EKUIInviteesViewTimeSlotCell {
    bool  _conflict;
}

@property bool conflict;

- (bool)conflict;
- (id)participantsTextColor;
- (void)setConflict:(bool)arg1;
- (id)timeTextColor;

@end
