/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKUIResizingDateLabel : UILabel {
    NSDate * _date;
}

@property (retain) NSDate *date;

- (void).cxx_destruct;
- (id)date;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)layoutSubviews;
- (double)minDateLabelWidth;
- (void)setDate:(id)arg1;
- (id)stringForDateThatFits;

@end
