/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BiometricKit.framework/BiometricKit
 */

@interface BKMatchOperation : BKOperation {
    bool  _captureOnly;
    NSData * _credentialSet;
    long long  _priority;
    long long  _purpose;
    NSArray * _selectedIdentities;
    bool  _stopOnSuccess;
    long long  _useCase;
    NSNumber * _userID;
}

@property (nonatomic) bool captureOnly;
@property (nonatomic, copy) NSData *credentialSet;
@property (nonatomic) <BKMatchOperationDelegate> *delegate;
@property (nonatomic) long long priority;
@property (nonatomic) long long purpose;
@property (nonatomic, copy) NSArray *selectedIdentities;
@property (nonatomic) bool stopOnSuccess;
@property (nonatomic) long long useCase;
@property (nonatomic, retain) NSNumber *userID;

- (void).cxx_destruct;
- (bool)captureOnly;
- (id)credentialSet;
- (void)dealloc;
- (id)init;
- (long long)priority;
- (long long)purpose;
- (void)registerNotification:(struct __CFString { }*)arg1;
- (id)selectedIdentities;
- (void)setCaptureOnly:(bool)arg1;
- (void)setCredentialSet:(id)arg1;
- (void)setPriority:(long long)arg1;
- (void)setPurpose:(long long)arg1;
- (void)setSelectedIdentities:(id)arg1;
- (void)setStopOnSuccess:(bool)arg1;
- (void)setUseCase:(long long)arg1;
- (void)setUserID:(id)arg1;
- (void)simulateMatching:(bool)arg1 type:(long long)arg2;
- (bool)stopOnSuccess;
- (long long)useCase;
- (id)userID;

@end
