/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SAML.framework/SAML
 */

@interface SAMLScoping : SAMLBaseElement

@property (nonatomic, readonly) NSString *getComplete;
@property (nonatomic, readonly) NSArray *idpList;
@property (nonatomic, readonly) NSNumber *proxyCount;
@property (nonatomic, readonly) NSArray *requesterIds;

+ (id)createElement:(id*)arg1;

- (void)addRequesterId:(id)arg1;
- (id)getComplete;
- (id)idpList;
- (id)proxyCount;
- (id)requesterIds;

@end
