/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriReferenceResolver.framework/SiriReferenceResolver
 */

@interface SiriReferenceResolver.BaseQueryMatcher : _TtCs12_SwiftObject {
    void equivalentTypesForEntityType;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  logger;
}

@end
