/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@interface ML3ContainerItem : ML3Entity

+ (id)databaseTable;
+ (id)defaultOrderingTerms;
+ (void)initialize;
+ (long long)revisionTrackingCode;

@end
