/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/VisionCore.framework/VisionCore
 */

@interface VisionCoreValidationUtilities : NSObject

+ (bool)validateObject:(id)arg1 isKindOfClass:(Class)arg2 basedOnClass:(Class)arg3 error:(id*)arg4;

@end
