/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/WebContentRestrictions.framework/WebContentRestrictions
 */

@interface WCRCipherMLClient : NSObject

+ (void)activateCipherML;
+ (id)categoryForCategoryLetter:(id)arg1;
+ (id)categoryForString:(id)arg1 withError:(id*)arg2;

@end
