/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MLRuntime.framework/MLRuntime
 */

@interface MLRSandboxExtensionRequest : NSObject {
    NSArray * _URLs;
    bool  _requireWrite;
}

@property (nonatomic, readonly, copy) NSArray *URLs;
@property (nonatomic, readonly) bool requireWrite;

- (void).cxx_destruct;
- (id)URLs;
- (id)description;
- (id)initWithURLs:(id)arg1 requireWrite:(bool)arg2;
- (bool)requireWrite;

@end
