/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ChronoServices.framework/ChronoServices
 */

@interface CHSApplicationProcessStateChangeConsumer : NSObject {
    CHSChronoServicesConnection * _connection;
}

- (void).cxx_destruct;
- (void)applicationWithBundleIdentifierEnteredForeground:(id)arg1;
- (id)init;
- (id)initWithConnection:(id)arg1;

@end
