/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ChronoServices.framework/ChronoServices
 */

@interface CHSEquivalentBundleIdentifierResolver : NSObject <CHSEquivalentBundleIdentifierResolving> {
    void categoriesPrimitives;
}

+ (id)defaultResolver;

- (void).cxx_destruct;
- (id)equivalentBundleIdentifiersForBundleIdentifier:(id)arg1;
- (id)init;
- (id)initWithCategoriesPrimitives:(id)arg1;

@end
