/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtC7SwiftUIP33_68550FF604D39F05971FE35A26EE75B013BoxVTableBase : _TtCs12_SwiftObject

@end
