/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.RBDisplayListDecoderDelegate : NSObject <RBDecoderDelegate> {
    void decoder;
}

- (void).cxx_destruct;
- (struct CGFont { }*)decodedCGFontWithData:(id)arg1 error:(id*)arg2;
- (id)decodedImageContentsWithData:(id)arg1 type:(int*)arg2 error:(id*)arg3;
- (id)init;

@end
