/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.EmptyViewRendererHost : _TtCs12_SwiftObject {
    void accessibilityVersion;
    void currentAccessibilityFocusStore;
    void currentTimestamp;
    void eventBindingManager;
    void externalUpdateCount;
    void focusedValues;
    void propertiesNeedingUpdate;
    void renderingPhase;
    void viewGraph;
}

@end
