/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface UIKitContainerFocusResponderItemBase : NSObject

- (id)_regionForFocusedItem:(id)arg1 inCoordinateSpace:(id)arg2;
- (void)_searchForFocusRegionsInContext:(id)arg1;
- (id)swiftui_regionForFocusedItem:(id)arg1 inCoordinateSpace:(id)arg2;
- (void)swiftui_searchForFocusRegionsInContext:(id)arg1;

@end
