/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Matter.framework/Matter
 */

@interface MTRBooleanStateClusterStateChangeEvent : NSObject <NSCopying> {
    NSNumber * _stateValue;
}

@property (nonatomic, copy) NSNumber *stateValue;

// MTRBooleanStateClusterStateChangeEvent (null)

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)init;
- (void)setStateValue:(id)arg1;
- (id)stateValue;

@end
