/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKDatabaseOperation : CKOperation {
    CKDatabase * _database;
}

@property (nonatomic, retain) CKDatabase *database;
@property (nonatomic, readonly) CKDatabaseOperationInfo *operationInfo;

- (void).cxx_destruct;
- (id)CKDescriptionPropertiesWithPublic:(bool)arg1 private:(bool)arg2 shouldExpand:(bool)arg3;
- (bool)CKOperationShouldRun:(id*)arg1;
- (id)database;
- (id)databaseIfNotNil;
- (long long)databaseScope;
- (void)fillFromOperationInfo:(id)arg1;
- (void)fillOutOperationInfo:(id)arg1;
- (void)setDatabase:(id)arg1;
- (bool)zoneIDHasCorrectDatabaseScope:(id)arg1 error:(id*)arg2;

@end
