/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@interface CKSQLiteReferencedObjectTable : CKSQLiteTable {
    CKSQLiteRefcountTable * _refcountTable;
}

- (void).cxx_destruct;
- (id)databaseReferenceValueForEntry:(id)arg1 error:(id*)arg2;
- (id)didCreateDatabaseTable;
- (id)entryForDatabaseReferenceValue:(id)arg1 error:(id*)arg2;
- (id)extraGroupTables:(id)arg1;
- (id)lookupRefcountTable;
- (unsigned long long)refcountForEntry:(id)arg1;
- (id)refcountTableName;
- (id)refcountTriggerSQLForProperty:(id)arg1 inTable:(id)arg2;
- (id)wakeFromDatabase;
- (id)willStoreReferenceToUnsavedEntry:(id)arg1;

@end
