/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CloudPhotoLibrary.framework/CloudPhotoLibrary
 */

@interface CPLExpungeableResourceState : NSObject <NSCopying, NSSecureCoding> {
    NSDate * _expungedDate;
    unsigned long long  _expungedState;
    unsigned long long  _resourceType;
}

@property (nonatomic, copy) NSDate *expungedDate;
@property (nonatomic) unsigned long long expungedState;
@property (nonatomic) unsigned long long resourceType;

+ (id)normalizedExpungeableResourceStatesFromExpungeableResourceStates:(id)arg1;

- (void).cxx_destruct;
- (id)description;
- (id)expungedDate;
- (unsigned long long)expungedState;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (unsigned long long)resourceType;
- (void)setExpungedDate:(id)arg1;
- (void)setExpungedState:(unsigned long long)arg1;
- (void)setResourceType:(unsigned long long)arg1;

// CPLExpungeableResourceState (CPLNSCoding)

+ (bool)supportsSecureCoding;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
