/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CloudPhotoLibrary.framework/CloudPhotoLibrary
 */

@interface CPLQuarantineFeedbackMessage : CPLFeedbackMessage {
    NSString * _reason;
    Class  _recordClass;
}

@property (nonatomic, readonly) NSString *reason;
@property (nonatomic, readonly) Class recordClass;

+ (id)feedbackType;

- (void).cxx_destruct;
- (id)initWithClass:(Class)arg1 reason:(id)arg2 libraryIdentifier:(id)arg3;
- (id)reason;
- (Class)recordClass;
- (id)serverMessage;

@end
