/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FeatureFlagsSupport.framework/FeatureFlagsSupport
 */

@interface FFDropFileWriter : NSObject <FFFileWriter>

- (bool)createDirectoryAtURL:(id)arg1 error:(id*)arg2;
- (bool)writeData:(id)arg1 toFile:(id)arg2 error:(id*)arg3;

@end
