/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppleMediaServicesUI.framework/AppleMediaServicesUI
 */

@interface AMSUIParentalVerificationCore : NSObject

+ (bool)_isCardOnFileOnStack:(id)arg1;
+ (id)_tokenFromObject:(id)arg1;
+ (id)_tokenResultFromTokenString:(id)arg1;

@end
