/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppleMediaServicesUI.framework/AppleMediaServicesUI
 */

@interface AMSUIParentalVerificationCommon : NSObject

+ (id)_promiseToPromptAfterFailureWithBag:(id)arg1 viewController:(id)arg2 metrics:(id)arg3 pageID:(id)arg4 flowName:(id)arg5;

@end
