/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriOntology.framework/SiriOntology
 */

@interface SiriOntology.Graph : _TtCs12_SwiftObject {
    void _startNode;
    void _vertexCounter;
    void edges;
    void nodeMap;
}

@end
