/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/DataDetection.framework/DataDetection
 */

@interface DDMatchEmailAddress : DDMatch {
    NSString * _emailAddress;
    NSString * _label;
}

@property (nonatomic, readonly) NSString *emailAddress;
@property (nonatomic, readonly) NSString *label;

- (void).cxx_destruct;
- (id)emailAddress;
- (id)initWithDDScannerResult:(id)arg1;
- (id)label;

@end
