/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSSpringBoardDefaults : BSAbstractDefaultDomain

@property (nonatomic) float brightness;

- (void)_bindAndRegisterDefaults;
- (id)init;

@end
