/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/VoiceShortcutClient.framework/VoiceShortcutClient
 */

@interface WFShortcutRunnerSandboxExtensionRequest : NSObject {
    NSSet * _accessResourceClassNames;
}

@property (nonatomic, readonly) NSSet *accessResourceClassNames;

+ (id)all;

- (void).cxx_destruct;
- (id)accessResourceClassNames;
- (id)initWithAccessResourceClassNames:(id)arg1;

@end
