/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/OSLog.framework/OSLog
 */

@interface OSLogEntryBoundary : OSLogEntry

+ (bool)supportsSecureCoding;

- (id)initWithCoder:(id)arg1;

@end
