/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PhotosIntelligence.framework/PhotosIntelligence
 */

@interface CLSAssetProcessedSignals_v5 : CLSAssetProcessedSignals_v4 <CLSSDProcessedSignals> {
    bool  _isShowcasingFood;
}

@property (nonatomic) bool isShowcasingFood;

- (bool)isShowcasingFood;
- (void)setIsShowcasingFood:(bool)arg1;

@end
