/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriTTSService.framework/SiriTTSService
 */

@interface OPTTSMutableTTSWordPhonemes : OPTTSTTSWordPhonemes

@property (nonatomic, copy) NSArray *phonemes;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (id)phonemes;
- (void)setPhonemes:(id)arg1;

@end
