/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/MusicKit.framework/MusicKit
 */

@interface MusicKit.AnyLibraryRequestConfigurationParameters : _TtCs12_SwiftObject {
    void allowedIdentifiers;
    void includeOnlyFavoritedContent;
    void propertyFilters;
    void resolvedSortDescriptors;
    void scopedContainers;
}

@end
