/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SetupAssistant.framework/SetupAssistant
 */

@interface BYLicenseAgreement : NSObject

+ (void)_clearAcceptedLicenseVersion;
+ (bool)needsToAcceptNewAgreement;
+ (void)recordUserAcceptedAgreementVersion:(unsigned long long)arg1;
+ (unsigned long long)versionOfAcceptedAgreement;
+ (unsigned long long)versionOfOnDiskAgreement;

@end
