/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFCoreAnalyticsLoggingService : NSObject {
    NSObject<OS_dispatch_queue> * _queue;
}

+ (id)sharedLoggingService;

- (void).cxx_destruct;
- (id)_init;
- (id)init;
- (void)logToCoreAnalyticsCrossDeviceRequestEvent:(id)arg1;

@end
