/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFConversationError : NSError

+ (id)errorWithCode:(long long)arg1;
+ (id)errorWithCode:(long long)arg1 localizedFailureReason:(id)arg2;
+ (id)errorWithCode:(long long)arg1 userInfo:(id)arg2;

- (id)initWithCode:(long long)arg1;
- (id)initWithCode:(long long)arg1 localizedFailureReason:(id)arg2;
- (id)initWithCode:(long long)arg1 userInfo:(id)arg2;

@end
