/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFFlowServiceConnection : NSObject {
    NSXPCConnection * _connection;
    unsigned long long  _pendingTransactionCount;
    NSObject<OS_dispatch_queue> * _queue;
}

+ (id)sharedConnection;

- (void).cxx_destruct;
- (void)_clearConnection;
- (id)_connection;
- (id)_init;
- (void)invokeMethodOnRemoteWithBlock:(id /* block */)arg1 onError:(id /* block */)arg2;

@end
