/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeechFoundation.framework/CoreSpeechFoundation
 */

@interface CSFCircularEventsCacheBuffer : NSObject {
    NSMutableArray * _eventsArray;
    long long  _lastEventIndex;
}

@property (nonatomic, readonly) NSMutableArray *eventsArray;

- (void).cxx_destruct;
- (void)addEventToCacheBuffer:(id)arg1;
- (void)clearBuffer;
- (id)eventsArray;
- (id)init;

@end
