/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GRDBInternal.framework/GRDBInternal
 */

@interface _TtCC12GRDBInternal8DatabaseP33_5A6CBE2AA28B02E3CEA065D55090729924FTS5TokenizerConstructor : _TtCs12_SwiftObject {
    void constructor;
    void db;
}

@end
