/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Intents.framework/Intents
 */

@interface INBillPayeeResolutionResult : INIntentResolutionResult

+ (id)confirmationRequiredWithBillPayeeToConfirm:(id)arg1;
+ (id)disambiguationWithBillPayeesToDisambiguate:(id)arg1;
+ (id)successWithResolvedBillPayee:(id)arg1;

- (id)_intentSlotValueForObject:(id)arg1 slotDescription:(id)arg2;
- (id)_vocabularyValueForObject:(id)arg1 slotDescription:(id)arg2;

@end
