/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Intents.framework/Intents
 */

@interface INSettingMetadataResolutionResult : INIntentResolutionResult

+ (id)confirmationRequiredWithSettingMetadataToConfirm:(id)arg1;
+ (id)disambiguationWithSettingMetadatasToDisambiguate:(id)arg1;
+ (id)successWithResolvedSettingMetadata:(id)arg1;

- (id)_intentSlotValueForObject:(id)arg1 slotDescription:(id)arg2;
- (id)_vocabularyValueForObject:(id)arg1 slotDescription:(id)arg2;

@end
