/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CloudKitDistributedSync.framework/CloudKitDistributedSync
 */

@interface CKAtomReferenceMutableProxy : CKXStructMutableProxyBase <CKXWriteStructProxy>

- (void)assignLocationFromProxy:(id)arg1;
- (void)assignTimestampFromProxy:(id)arg1;
- (void)copyFromReadProxy:(id)arg1;
- (void)copyFromReference:(id)arg1;
- (id)location;
- (void)setType:(unsigned char)arg1;
- (id)timestamp;

@end
