/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CloudKitDistributedSync.framework/CloudKitDistributedSync
 */

@interface CKDistributedSiteIdentifierMutableProxy : CKXStructMutableProxyBase <CKXWriteStructProxy>

- (void)copyFromReadProxy:(id)arg1;
- (void)copyFromSiteIdentifier:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setIdentifierBytes:(void*)arg1 length:(unsigned long long)arg2;
- (void)setModifier:(id)arg1;
- (void)setModifierBytes:(void*)arg1 length:(unsigned long long)arg2;

@end
