/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal
 */

@interface CDPDTermsInfoBackupController : NSObject

- (id)_buildSecureBackupTermsInfo:(id)arg1;
- (void)fetchTermsAcceptanceForAccount:(id)arg1 completion:(id /* block */)arg2;
- (void)saveTermsAcceptance:(id)arg1 completion:(id /* block */)arg2;

@end
