/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NanoRegistry.framework/NanoRegistry
 */

@interface NRConnectivitySubscriber : NSObject {
    bool  _connected;
    unsigned long long  _dropoutCounter;
}

+ (bool)getDropoutCounter:(unsigned long long*)arg1;

- (id)init;

@end
