/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NanoRegistry.framework/NanoRegistry
 */

@interface NRDeviceMiniStore : NSObject <NSSecureCoding> {
    NSDictionary * _store;
}

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)fullStore;
- (id)initWithCoder:(id)arg1;
- (id)initWithStore:(id)arg1;
- (id)objectForKey:(id)arg1;

@end
