/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/ShazamKit.framework/ShazamKit
 */

@interface SHShazamCatalog : SHCatalog

+ (id)new;

- (id)_createMatcher;
- (id)init;

@end
