/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/Trial.framework/Trial
 */

@interface TRIPersistedFactorsState : TRIPBMessage

@property (nonatomic, retain) TRIPersistedBMLTFactorsState *bmlt;
@property (nonatomic, retain) TRIPersistedExperimentFactorsState *experiment;
@property (nonatomic, retain) TRIPersistedRolloutFactorsState *rollout;
@property (nonatomic, readonly) int stateOneOfCase;

+ (id)descriptor;

@end
