/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/Trial.framework/Trial
 */

@interface TRISystemInfoGuardedData : NSObject {
    bool  isStale;
    TRISystemInfo * systemInfo;
}

- (void).cxx_destruct;

@end
