/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

@interface VSDownloadOptions : NSObject {
    bool  _allowCellularData;
    bool  _allowDiscretionary;
}

@property (nonatomic) bool allowCellularData;
@property (nonatomic) bool allowDiscretionary;

- (bool)allowCellularData;
- (bool)allowDiscretionary;
- (void)setAllowCellularData:(bool)arg1;
- (void)setAllowDiscretionary:(bool)arg1;

@end
