/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/BiomeLibrary.framework/BiomeLibrary
 */

@interface BMClockAlarm_v1 : BMClockAlarm

- (int)eventType;
- (int)lastEventType;

@end
