/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MessageProtection.framework/MessageProtection
 */

@interface PublicKey : NSObject {
    <P256PublicKeyProtocol> * _key;
}

@property (retain) <P256PublicKeyProtocol> *key;

- (void).cxx_destruct;
- (id)dataRepresentation;
- (id)description;
- (id)initWithData:(id)arg1 error:(id*)arg2;
- (id)initWithKey:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)key;
- (void)setKey:(id)arg1;

@end
