/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CalendarUIKit.framework/CalendarUIKit
 */

@interface CUIKSplashScreenStrings : NSObject

+ (id)configurationText;
+ (id)continueButtonText;
+ (id)suggestedEventsFeatureText;
+ (id)suggestedEventsTitleText;
+ (id)suggestedLocationsFeatureText;
+ (id)suggestedLocationsTitleText;
+ (id)timeToLeaveAndAutomaticGeocodingFeatureText;
+ (id)timeToLeaveAndAutomaticGeocodingTitleText;
+ (id)title;

@end
