/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CalendarUIKit.framework/CalendarUIKit
 */

@interface CUIKSuggestionCoalescedInfo : NSObject {
    NSString * _descriptionText;
    EKCalendarSuggestionNotification * _earliestSuggestionNotification;
    NSString * _title;
}

@property (readonly) NSString *descriptionText;
@property (readonly) EKCalendarSuggestionNotification *earliestSuggestionNotification;
@property (readonly) NSString *title;

- (void).cxx_destruct;
- (id)descriptionText;
- (id)earliestSuggestionNotification;
- (id)initWithTitle:(id)arg1 descriptionText:(id)arg2 earliestSuggestionNotification:(id)arg3;
- (id)title;

@end
