/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CalendarUIKit.framework/CalendarUIKit
 */

@interface CUIKCalendarListSorter : NSObject

+ (id /* block */)ekCalendarComparator;
+ (id /* block */)ekOtherCalendarComparator;
+ (id /* block */)ekSourceComparator;
+ (long long)orderForOtherCalendar:(id)arg1;

@end
