/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/Navigation.framework/Navigation
 */

@interface MNRouteDivergenceResults : NSObject {
    NSArray * _results;
    NSUUID * _routeID;
}

@property (nonatomic, retain) NSArray *results;
@property (nonatomic, retain) NSUUID *routeID;

- (void).cxx_destruct;
- (id)description;
- (id)results;
- (id)routeID;
- (void)setResults:(id)arg1;
- (void)setRouteID:(id)arg1;

@end
