/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libxpc.dylib
 */

@interface OS_xpc_listener : OS_object

- (void)_xref_dispose;
- (void)dealloc;
- (id)description;
- (id)init;
- (oneway void)release;

@end
