/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/HomeKitMetrics.framework/HomeKitMetrics
 */

@interface HMMHomeLogEvent : HMMLogEvent {
    NSUUID * _homeUUID;
}

@property (nonatomic, readonly) NSUUID *homeUUID;
@property (nonatomic, readonly) NSString *homeUUIDString;

+ (id)alloc;

- (void).cxx_destruct;
- (id)homeUUID;
- (id)homeUUIDString;
- (id)initWithHomeUUID:(id)arg1;

@end
