/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FamilyCircle.framework/FamilyCircle
 */

@interface FAHandleFamilyEventPushNotificationRequest : FAFamilyCircleRequest {
    NSDictionary * _payload;
}

@property (readonly) NSDictionary *payload;

- (void).cxx_destruct;
- (id)initWithPayload:(id)arg1;
- (id)payload;
- (void)startRequestWithCompletionHandler:(id /* block */)arg1;

@end
