/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@interface BRCDatabaseRestoreManager : NSObject {
    NSURL * _clientDatabaseURL;
    NSURL * _userURL;
}

@property (nonatomic, retain) NSURL *clientDatabaseURL;
@property (nonatomic, retain) NSURL *userURL;

- (void).cxx_destruct;
- (id)clientDatabaseURL;
- (id)initWithUserURL:(id)arg1;
- (void)restoreWithCompletionBlock:(id /* block */)arg1;
- (void)setClientDatabaseURL:(id)arg1;
- (void)setUserURL:(id)arg1;
- (id)userURL;

@end
