/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@interface BRCZoneRootItem : BRCDirectoryItem <BRCFSRooted>

- (id)asFSRoot;
- (id)extendedAttributes;
- (id)fileID;
- (id)initWithZoneRootItemID:(id)arg1 session:(id)arg2;
- (bool)isDirectoryFault;
- (bool)isFSRoot;
- (bool)isShareableItem;
- (bool)isUserVisible;
- (bool)isZoneRoot;
- (unsigned char)itemScope;
- (id)parentItemID;
- (id)parentItemOnFS;
- (bool)saveToDB;
- (id)st;

@end
