/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppStoreDaemon.framework/AppStoreDaemon
 */

@interface ASDClipMetricsCoordinator : NSObject {
    <ASDClipServiceBroker> * _broker;
}

- (void).cxx_destruct;
- (id)init;
- (void)sendClipCardMetricsEvent:(id)arg1 completionHandler:(id /* block */)arg2;

@end
