/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AppStoreDaemon.framework/AppStoreDaemon
 */

@interface ASDJobSchedulerRequest : ASDEphemeralRequest

+ (long long)requestType;

- (void)findNextJobsWithCompletionBlock:(id /* block */)arg1;
- (id)initWithOptions:(id)arg1;

@end
