/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNGeminiBadge : CNLabeledBadge

@property (nonatomic, copy) NSDictionary *viewAttributes;

+ (id)geminiBadgeWithText:(id)arg1;

- (void)setViewAttributes:(id)arg1;
- (id)viewAttributes;

@end
