/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNPRUISPosterSnapshotController : NSObject

- (void)acquireKeepActiveAssertionForReason:(id)arg1;
- (void)executeSnapshotRequest:(id)arg1 completion:(id /* block */)arg2;
- (id)latestSnapshotBundleForRequest:(id)arg1 error:(out id*)arg2;
- (void)releaseKeepActiveAssertionForReason:(id)arg1;
- (id)sharedController;

@end
