/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MediaMiningKit.framework/MediaMiningKit
 */

@interface CLSNowPlayingStreamEventClusteringParameters : NSObject {
    unsigned long long  _algorithm;
    double  _minimumClusteringTimeInSeconds;
}

@property (nonatomic) unsigned long long algorithm;
@property (nonatomic) double minimumClusterTimeInSeconds;

- (unsigned long long)algorithm;
- (id)init;
- (double)minimumClusterTimeInSeconds;
- (void)setAlgorithm:(unsigned long long)arg1;
- (void)setMinimumClusterTimeInSeconds:(double)arg1;

@end
