/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreSpotlight.framework/CoreSpotlight
 */

@interface CSDocumentUnderstandingCategory : CSExternalAnalysisTag <CSCoderEncoder>

- (id)initWithLabel:(id)arg1 synonyms:(id)arg2 confidence:(double)arg3;

// CSDocumentUnderstandingCategory (CSCoderAdditions)

- (void)encodeWithCSCoder:(id)arg1;

@end
