/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Metal.framework/Metal
 */

@interface _MTLImageBlockArguments : NSObject {
    unsigned long long  _height;
    unsigned long long  _width;
}

@property (nonatomic) unsigned long long height;
@property (nonatomic) unsigned long long width;

- (unsigned long long)height;
- (void)setHeight:(unsigned long long)arg1;
- (void)setWidth:(unsigned long long)arg1;
- (unsigned long long)width;

@end
