/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TrustedPeers.framework/TrustedPeers
 */

@interface TPStringTable : NSObject {
    NSObject<OS_dispatch_queue> * _queue;
    NSHashTable * _table;
}

@property (readonly) unsigned long long _count;
@property (retain) NSObject<OS_dispatch_queue> *queue;
@property (retain) NSHashTable *table;

+ (id)defaultTable;

- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1;
- (id)queue;
- (void)setQueue:(id)arg1;
- (void)setTable:(id)arg1;
- (id)setWithArray:(id)arg1;
- (id)stringWithString:(id)arg1;
- (id)table;

// TPStringTable (Testing)

- (unsigned long long)_count;

@end
