/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CryptoTokenKit.framework/CryptoTokenKit
 */

@interface TKLocalSEPKey : TKSEPKey {
    id  _accessControl;
    NSXPCConnection * _caller;
    id  _keyHolder;
    id  _keyType;
    bool  _systemSessionKey;
}

@property (nonatomic, readonly) NSXPCConnection *caller;
@property (nonatomic, readonly) struct __SecKey { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct __SecKeyDescriptor {} *x2; void *x3; }*key;

+ (bool)hasSEP;
+ (void)runsInSystemSession;
+ (void)setContextErrorHandler:(id /* block */)arg1;
+ (void)set_testing_callerEntitlements:(id)arg1;
+ (void)setupKeybagForTesting:(bool)arg1;

- (void).cxx_destruct;
- (id)_initWithKeyType:(id)arg1 keySize:(long long)arg2 accessControl:(struct __SecAccessControl { }*)arg3 options:(id)arg4 authContext:(id)arg5 caller:(id)arg6 forceSystemSession:(bool)arg7 error:(id*)arg8;
- (id)_initWithObjectID:(id)arg1 authContext:(id)arg2 caller:(id)arg3 forceSystemSession:(bool)arg4 error:(id*)arg5;
- (struct __SecAccessControl { }*)accessControl;
- (id)attestKey:(id)arg1 nonce:(id)arg2 error:(id*)arg3;
- (id)caller;
- (id)computeSharedSecret:(id)arg1 error:(id*)arg2;
- (bool)deleteWithError:(id*)arg1;
- (struct __SecKey { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct __SecKeyDescriptor {} *x2; void *x3; }*)key;
- (long long)keySize;
- (id)keyType;
- (bool)lifetimeControlWithType:(long long)arg1 error:(id*)arg2;
- (id)objectID;
- (id)publicKeyWithError:(id*)arg1;
- (id)recryptData:(id)arg1 attributes:(id)arg2 error:(id*)arg3;
- (id)signDigest:(id)arg1 error:(id*)arg2;
- (bool)systemKey;
- (bool)systemSessionKey;

@end
