/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CryptoTokenKit.framework/CryptoTokenKit
 */

@interface TKSimpleTLVRecord : TKTLVRecord

+ (id)parseFromDataSource:(id)arg1 error:(id*)arg2;

- (id)initWithTag:(unsigned char)arg1 value:(id)arg2;

@end
