/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SceneKit.framework/SceneKit
 */

@interface SCNIKJoint : NSObject {
    SCNNode * joint;
    double  maxAllowedRotationAngle;
}

@property (nonatomic) SCNNode *joint;
@property (nonatomic) double maxAllowedRotationAngle;

- (id)joint;
- (double)maxAllowedRotationAngle;
- (void)setJoint:(id)arg1;
- (void)setMaxAllowedRotationAngle:(double)arg1;

@end
