/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIFocusActiveSceneObserver : _UIFocusStateObserver {
    UIScene * _scene;
}

- (void).cxx_destruct;
- (id)_initWithScene:(id)arg1;
- (void)beginMonitoringContextChangesForWindow:(id)arg1;
- (id)init;
- (id)initWithScene:(id)arg1;
- (void)stopMonitoringContextChangesForWindow:(id)arg1;

@end
