/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIImageSystemImageVisualStyle : NSObject {
    UIImage * _actionsImage;
    UIImage * _addImage;
    UIImage * _checkmarkImage;
    UIImage * _removeImage;
    UIImage * _strokedCheckmarkImage;
}

- (void).cxx_destruct;

@end
