/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIInterfaceActionBlendingBorderView : _UIBlendingHighlightView

+ (bool)isBorderView;
+ (id)newWithRoundedCornerPosition:(unsigned long long)arg1 continuousCornerRadius:(double)arg2;

@end
