/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIInterfaceActionSelectionDelayGestureRecognizer : UIGestureRecognizer {
    UIDelayedAction * _delayedAction;
}

@property (nonatomic, readonly) UIDelayedAction *delayedAction;

- (void).cxx_destruct;
- (void)_timerSatisfied;
- (id)delayedAction;
- (void)reset;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end
