/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIModifierKeyCursorAccessory : _UICursorAccessory {
    long long  _modifierType;
}

@property (nonatomic) long long modifierType;

- (id)_modifierKeyCursorAccessory;
- (id)descriptionBuilder;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)identifier;
- (id)initWithCoder:(id)arg1;
- (long long)modifierType;
- (void)setModifierType:(long long)arg1;

@end
