/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UINavigationControllerVisualStyleWatchOS : _UINavigationControllerVisualStyle {
    <UIViewControllerInteractiveTransitioning> * _interactionController;
    <UIViewControllerAnimatedTransitioning> * _transitionController;
}

- (void).cxx_destruct;
- (id)interactionController;
- (bool)isUsingParallaxTransition;
- (void)setInteractionController:(id)arg1;
- (void)setTransitionController:(id)arg1;
- (id)transitionController;

@end
