/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UINavigationBarStarkVisualStyle : _UINavigationBarVisualStyle

- (double)backIndicatorBottomMargin;
- (double)buttonHeight;
- (double)horizontalMarginAdjustment;
- (double)imageButtonMarginInNavigationBar:(id)arg1;
- (double)leftBackTitleMargin;
- (double)leftTitleMargin;
- (long long)navigationBar:(id)arg1 metricsForOrientation:(long long)arg2 hasPrompt:(bool)arg3;
- (double)textButtonMarginInNavigationBar:(id)arg1;
- (double)topMargin;
- (double)topTitleMargin;

@end
