/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UISearchTextFieldCanvasView : _UITextFieldCanvasView {
    NSMutableSet * _atomViews;
}

- (void).cxx_destruct;
- (double)_uiatom_currentScreenScale;
- (void)_updateTokenViews;
- (void)layoutSubviews;

@end
