/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UISearchBarSearchContainerView : UIView {
    bool  _frozenLayout;
    _UISearchBarSearchContainerLayout * _layout;
    bool  _needsLayoutWhenThawed;
}

@property (nonatomic) bool frozenLayout;
@property (nonatomic, retain) _UISearchBarSearchContainerLayout *layout;

- (void).cxx_destruct;
- (id)description;
- (bool)frozenLayout;
- (id)layout;
- (void)layoutSubviews;
- (void)setFrozenLayout:(bool)arg1;
- (void)setLayout:(id)arg1;
- (void)setNeedsLayout;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

// _UISearchBarSearchContainerView (_UISearchBarCompatibilityClippingViewSupport)

- (bool)_isKnownUISearchBarComponentContainer;

@end
