/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarDisplayItemPlacementIndicatorsGroup : _UIStatusBarDisplayItemPlacementGroup {
    _UIStatusBarDisplayItemPlacement * _bluetoothInsetPaddingItem;
    NSArray * _stablePlacements;
    NSArray * _unstablePlacements;
}

@property (nonatomic, readonly) _UIStatusBarDisplayItemPlacement *bluetoothInsetPaddingItem;
@property (nonatomic, readonly, copy) NSArray *stablePlacements;
@property (nonatomic, readonly, copy) NSArray *unstablePlacements;

+ (id)activityItemDisplayIdentifier;
+ (id)groupWithHighPriority:(long long)arg1 lowPriority:(long long)arg2 bluetoothPaddingInset:(double)arg3;

- (void).cxx_destruct;
- (id)bluetoothInsetPaddingItem;
- (id)stablePlacements;
- (id)unstablePlacements;

@end
