/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UITextFieldClearButton : UIButton {
    <_UITextFieldClearButtonImageProviding> * _imageProvider;
}

@property (nonatomic) <_UITextFieldClearButtonImageProviding> *imageProvider;

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

+ (Class)_visualProviderClass;

- (void).cxx_destruct;
- (id)_defaultImageForState:(unsigned long long)arg1 withConfiguration:(id)arg2;
- (bool)_isModernButton;
- (id)imageProvider;
- (void)setImageProvider:(id)arg1;
- (void)setPointerInteractionEnabled:(bool)arg1;

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

- (id)accessibilityLabel;

// _UITextFieldClearButton (SafeCategory)

+ (Class)safeCategoryBaseClass;

@end
