/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIVisualEffectAlphaEntry : _UIVisualEffectViewEntry {
    double  _finalAlpha;
    double  _initialAlpha;
}

- (void)addEffectToView:(id)arg1;
- (void)applyIdentityEffectToView:(id)arg1;
- (void)applyRequestedEffectToView:(id)arg1;
- (id)copyForTransitionOut;
- (id)copyForTransitionToEffect:(id)arg1;
- (id)description;
- (id)initWithInitialAlpha:(double)arg1 finalAlpha:(double)arg2;
- (void)removeEffectFromView:(id)arg1;

@end
