/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIFocusContainerGuide : UIFocusGuide

- (bool)_isEligibleForFocusInteraction;
- (bool)_legacy_isEligibleForFocusInteraction;
- (void)_searchForFocusRegionsInContext:(id)arg1;
- (id)init;

@end
