/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKBRenderFactoryHWR_Floating : UIKBRenderFactoryHWR_Portrait

- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;

@end
