/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKBRenderFactory10Key_LandscapeTruffle : UIKBRenderFactory10Key_Landscape

- (double)capitalAbcSymbolSize;
- (double)centerColumnWidthFactor;
- (double)controlColumnWidthFactor;

@end
