/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKeyboardUIClient : NSObject {
    BSServiceConnection<BSServiceConnectionClient> * _connection;
    <UIKeyboardUIServiceProtocol> * _remoteTarget;
}

+ (id)serviceInterface;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_initConnectionIfNeeded;
- (void)dealloc;
- (id)init;
- (void)setKeyboardAlpha:(double)arg1 force:(bool)arg2;
- (id)snapshotViewForOptions:(unsigned long long)arg1;

@end
