/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIStatusBarElectronicTollCollectionItemView : UIStatusBarItemView {
    bool  _available;
}

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib

- (double)alphaForAvailable:(bool)arg1;
- (id)contentsImage;
- (void)setVisible:(bool)arg1;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

@end
