/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PhoneNumberResolver.framework/PhoneNumberResolver
 */

@interface PNRUtils : NSObject

+ (void)_countryCodeFromInternationalCode:(id)arg1 result:(id /* block */)arg2;
+ (id)_currentCountry;
+ (id)_currentLocale;
+ (bool)_isValidPhoneNumber:(id)arg1;
+ (void)_localizedCountryNameForISOCountryCode:(id)arg1 result:(id /* block */)arg2;
+ (id)_preferredLanguages;
+ (id)_stringByStrippingFormattingAndNotVisiblyAllowable:(id)arg1;

@end
