/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ContactsAutocomplete.framework/ContactsAutocomplete
 */

@interface CNAutocompleteCalendarServerOperationFactory : NSObject

- (id)eventKitDirectorySearchOperationForSource:(id)arg1 query:(id)arg2 resultsBlock:(id /* block */)arg3;

@end
