/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GameControllerSettings.framework/GameControllerSettings
 */

@interface GCSCopilotFusedController : NSObject <GCSJSONSerializable, NSSecureCoding> {
    NSString * _copilotIdentifier;
    NSString * _fusedControllerIdentifier;
    NSDate * _modifiedDate;
    NSString * _pilotIdentifier;
}

@property (nonatomic, readonly, copy) NSString *copilotIdentifier;
@property (nonatomic, readonly, copy) NSString *fusedControllerIdentifier;
@property (nonatomic, readonly) <GCSJSONObject> *jsonObject;
@property (nonatomic, readonly) NSDate *modifiedDate;
@property (nonatomic, readonly, copy) NSString *pilotIdentifier;

- (void).cxx_destruct;
- (id)copilotIdentifier;
- (id)description;
- (id)fusedControllerIdentifier;
- (id)initWithFusedControllerIdentifier:(id)arg1 pilotIdentifier:(id)arg2 copilotIdentifier:(id)arg3;
- (id)modifiedDate;
- (id)pilotIdentifier;

// GCSCopilotFusedController (GCSJSONSerializable)

- (id)initWithJSONObject:(id)arg1;
- (id)jsonObject;

// GCSCopilotFusedController (NSSecureCoding)

+ (id)archivalClasses;
+ (bool)supportsSecureCoding;

- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
