/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Accounts.framework/Accounts
 */

@interface ACDManagedCredentialItem : NSManagedObject

@property (nonatomic, retain) NSString *accountIdentifier;
@property (nonatomic, retain) NSDate *expirationDate;
@property (nonatomic, retain) NSNumber *persistent;
@property (nonatomic, retain) NSString *serviceName;

@end
