/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface _FBDarkBootHelper : NSObject

- (void)_setDarkBootEnabled:(bool)arg1;
- (void)clearBootedDark;
- (bool)isBootingDark;
- (void)setNextBootDark;

@end
