/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PDS.framework/PDS
 */

@interface PDSXPCInterface : NSObject

+ (id)_internalInterfaceFromVendor:(id)arg1;
+ (id)_standardInterfaceFromVendor:(id)arg1;
+ (id)handShakeInterfaceFromVendor:(id)arg1;

@end
