/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ProxCardKit.framework/ProxCardKit
 */

@interface PRXScannerViewController : PRXCardContentViewController {
    PRXScannerIndicatorView * _indicatorView;
    UIViewController * _scannerEngine;
}

@property (nonatomic, readonly) PRXScannerIndicatorView *indicatorView;
@property (nonatomic, readonly) UIViewController *scannerEngine;

- (void).cxx_destruct;
- (id)indicatorView;
- (id)initWithScannerEngine:(id)arg1;
- (void)resetConfirmationRing;
- (id)scannerEngine;
- (void)showConfirmationRing;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
