/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSCKRecordZone : NSObject <NSCopying, NSSecureCoding> {
    IDSCKRecordZoneID * _zoneID;
}

@property (nonatomic, readonly) IDSCKRecordZoneID *zoneID;

+ (Class)__class;
+ (id)alloc;

- (void).cxx_destruct;
- (id)zoneID;

@end
