/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSGFTMetricsReferencePointEvent : NSObject {
    NSNumber * _reason;
    NSNumber * _time;
}

@property (copy) NSNumber *reason;
@property (copy) NSNumber *time;

- (void).cxx_destruct;
- (id)description;
- (id)initWithTime:(id)arg1 reason:(id)arg2;
- (id)reason;
- (void)setReason:(id)arg1;
- (void)setTime:(id)arg1;
- (id)time;

@end
