/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSTransportScoreCard : NSObject <NSCopying> {
    bool  alreadySelected;
    unsigned int  interfaceIndex;
    bool  isIPv6;
    unsigned long long  score;
    long long  stunTransport;
    long long  transportInterface;
}

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
