/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Network.framework/Network
 */

@interface NWURLErrorUserInfoDictionary : NSDictionary {
    NWURLError * _error;
}

@property (nonatomic, retain) NWURLError *error;

- (void).cxx_destruct;
- (unsigned long long)count;
- (id)error;
- (id)initWithError:(id)arg1;
- (id)keyEnumerator;
- (id)objectForKey:(id)arg1;
- (void)setError:(id)arg1;

@end
