/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

@interface CalDAVCalendarServerInviteItem : CoreDAVItem {
    NSMutableSet * _users;
}

@property (nonatomic, retain) NSMutableSet *users;

- (void).cxx_destruct;
- (void)addUser:(id)arg1;
- (id)copyParseRules;
- (id)init;
- (id)initWithNameSpace:(id)arg1 andName:(id)arg2;
- (void)setUsers:(id)arg1;
- (id)users;

@end
