/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NetAppsUtilities.framework/NetAppsUtilities
 */

@interface NAFilterEnumerator : NSEnumerator {
    NSEnumerator * _enumerator;
    id /* block */  _filter;
}

@property (nonatomic, readonly) NSEnumerator *enumerator;
@property (nonatomic, readonly, copy) id /* block */ filter;

- (void).cxx_destruct;
- (id)allObjects;
- (id)enumerator;
- (id /* block */)filter;
- (id)initWithEnumerator:(id)arg1 filter:(id /* block */)arg2;
- (id)nextObject;

@end
