/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/JetEngine.framework/JetEngine
 */

@interface _TtCO9JetEngine8Unstable8Accounts : _TtCs12_SwiftObject {
    void accountsLock;
    void backingStore;
    void unlockedActiveiTunesAccount;
}

- (void)accountCookiesDidChange:(id)arg1;
- (void)accountStoreDidChange:(id)arg1;

@end
