/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/EmailFoundation.framework/EmailFoundation
 */

@interface EFProcessBoost : NSObject {
    id /* block */  _boost;
}

- (void).cxx_destruct;
- (void)drop;
- (id)initWithBoost:(id /* block */)arg1;

@end
