/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface BlockDeallocator : NSObject {
    id /* block */  _block;
}

- (void)dealloc;
- (id)initWithBlock:(id /* block */)arg1;

@end
