/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIColorPolynomialInverse : CIColorPolynomial

+ (id)customAttributes;

- (bool)_isInvertible;
- (id)_kernel;
- (id)_kernelRGB;
- (id)outputImage;

@end
