/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIPaperWash : CIFilter {
    NSNumber * inputGreyscale;
    CIImage * inputImage;
    NSNumber * inputSaturation;
}

@property (nonatomic, copy) NSNumber *inputGreyscale;
@property (nonatomic, copy) NSNumber *inputSaturation;

+ (id)customAttributes;

- (id)inputGreyscale;
- (id)inputSaturation;
- (id)outputImage;
- (void)setInputGreyscale:(id)arg1;
- (void)setInputSaturation:(id)arg1;

@end
