/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TemplateKit.framework/TemplateKit
 */

@interface TLKDetailsSection : TLKObject {
    NSArray * _details;
    TLKMultilineText * _title;
}

@property (nonatomic, retain) NSArray *details;
@property (nonatomic, retain) TLKMultilineText *title;

- (void).cxx_destruct;
- (id)details;
- (void)setDetails:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end
