/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TemplateKit.framework/TemplateKit
 */

@interface TLKKeyValueGridView : NUIContainerGridView {
    NSMutableArray * _keyLabels;
    NSMutableArray * _valueLabels;
}

@property (nonatomic, retain) NSMutableArray *keyLabels;
@property (nonatomic, retain) NSMutableArray *valueLabels;

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TemplateKit.framework/TemplateKit

- (void).cxx_destruct;
- (id)init;
- (id)keyLabels;
- (void)setKeyLabels:(id)arg1;
- (void)setValueLabels:(id)arg1;
- (void)updateWithTuples:(id)arg1 valueColumnIsTrailing:(bool)arg2 truncateKey:(bool)arg3;
- (id)valueLabels;

// Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/AccessibilityBundles/TemplateKit.axbundle/TemplateKit

- (id)accessibilityElements;

// TLKKeyValueGridView (SafeCategory)

+ (Class)safeCategoryBaseClass;

@end
