/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/HealthDaemonFoundation.framework/HealthDaemonFoundation
 */

@interface _HDContentProtectionObserverWrapper : NSObject {
    <HDContentProtectionObserver> * _observer;
    NSObject<OS_dispatch_queue> * _queue;
}

- (void).cxx_destruct;
- (id)init;

@end
