/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/HomeKitMatter.framework/HomeKitMatter
 */

@interface HMMTROperationWithPriority : NSOperation {
    id /* block */  _operationBlock;
}

@property (nonatomic, readonly) id /* block */ operationBlock;

- (void).cxx_destruct;
- (id)initWithQueuePriority:(long long)arg1 block:(id /* block */)arg2;
- (void)main;
- (id /* block */)operationBlock;

@end
