/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NSHTTPCookieStorageInternal : NSObject {
    NSRecursiveLock * dataLock;
    bool  privateBrowsing;
    struct OpaqueCFHTTPCookieStorage { } * privateStorage;
    struct OpaqueCFHTTPCookieStorage { } * storage;
}

- (void)_syncCookies;
- (void)dealloc;
- (void)registerForPostingNotificationsWithContext:(id)arg1;

@end
