/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreHAP.framework/CoreHAP
 */

@interface HAPTLVDescription : HMFObject

- (id)description;
- (void)description:(id)arg1 indent:(id)arg2;
- (id)descriptionWithIndent:(id)arg1;

@end
