/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
 */

@interface ACDAutoBugCapture : NSObject

+ (void)triggerAutoBugCaptureWithType:(id)arg1 subType:(id)arg2 subtypeContext:(id)arg3 detectedProcess:(id)arg4;

@end
