/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GPUToolsTransport.framework/GPUToolsTransport
 */

@interface GTLoopbackServiceXPCProxy : NSObject <GTLoopbackService> {
    GTServiceConnection * _connection;
}

- (void).cxx_destruct;
- (id)echo:(id)arg1;
- (void)echo:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)echo:(id)arg1 repeat:(unsigned long long)arg2 callback:(id /* block */)arg3;
- (void)echo:(id)arg1 repeat:(unsigned long long)arg2 callback:(id /* block */)arg3 complete:(id /* block */)arg4;
- (id)initWithConnection:(id)arg1 remoteProperties:(id)arg2;

@end
