/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface _HDStatisticsCollectionQueryPendingSeries : NSObject {
    NSNumber * _anchor;
    NSMutableArray * _quantities;
    HKQuantitySample * _series;
}

- (void).cxx_destruct;

@end
