/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface _HDWorkoutCondensationConfiguration : NSObject {
    _HDWorkoutCondenserAnalyticsAccumulator * _analyticsAccumulator;
    long long  _deletedSampleThreshold;
    long long  _maximumSeriesSize;
    long long  _minimumSeriesSize;
    double  _minimumWorkoutDuration;
    HDSQLitePredicate * _predicate;
    HDProfile * _profile;
}

- (void).cxx_destruct;

@end
