/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDDataCollectorRecord : NSObject {
    <HDDataCollector> * _collector;
    HDDataCollectorState * _state;
}

@property (nonatomic) <HDDataCollector> *collector;
@property (nonatomic, retain) HDDataCollectorState *state;

- (void).cxx_destruct;
- (id)collector;
- (id)description;
- (void)setCollector:(id)arg1;
- (void)setState:(id)arg1;
- (id)state;

@end
