/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDHeartRateDataAggregator : HDDataAggregator

- (id)configurationForCollector:(id)arg1;
- (void)dataCollector:(id)arg1 didCollectSensorData:(id)arg2 device:(id)arg3;
- (void)dealloc;
- (id)initWithDataCollectionManager:(id)arg1;
- (id)objectType;
- (void)setConfiguration:(id)arg1;
- (void)workoutManagerStateChanged:(id)arg1;

@end
