/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriNaturalLanguageParsing.framework/SiriNaturalLanguageParsing
 */

@interface SNLPPommesServerClassifier : SNLPITFMClassifier {
    float  _confidenceThreshold;
}

@property (nonatomic) float confidenceThreshold;

+ (id /* block */)_initializationBlock;
+ (id)classifierWithPathURL:(id)arg1 error:(id*)arg2;

- (float)confidenceThreshold;
- (id)responseForRequest:(id)arg1 error:(id*)arg2;
- (void)setConfidenceThreshold:(float)arg1;

@end
