/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriNaturalLanguageParsing.framework/SiriNaturalLanguageParsing
 */

@interface UPIntentWithSingleEntity : NSObject {
    UPEntityWithValue * _entity;
    NSString * _intent;
}

@property (readonly) UPEntityWithValue *entity;
@property (readonly) NSString *intent;

- (void).cxx_destruct;
- (id)entity;
- (id)initWithIntent:(id)arg1 singleEntity:(id)arg2;
- (id)intent;
- (bool)isEqualToIntentWithSingleEntity:(id)arg1;

@end
