/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/RTCReporting.framework/RTCReporting
 */

@interface UpdateAndReportServices : NSObject {
    id /* block */  _block;
    bool  _report;
    bool  _update;
}

@property (copy) id /* block */ block;
@property (readonly) bool report;
@property (readonly) bool update;

- (id /* block */)block;
- (void)dealloc;
- (id)initWithServices:(bool)arg1 needToReport:(bool)arg2 service:(id /* block */)arg3;
- (bool)report;
- (void)setBlock:(id /* block */)arg1;
- (bool)update;

@end
