/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface FigCaptureInternalSinkConfiguration : FigCaptureSinkConfiguration {
    int  _subType;
}

@property (nonatomic, readonly) int subType;

- (id)initWithSinkSubType:(int)arg1;
- (int)sinkType;
- (int)subType;

@end
