/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ShareSheet.framework/ShareSheet
 */

@interface SHSheetActivityPresentationContext : NSObject {
    bool  _isCloudSharing;
    bool  _shouldDismissBeforePresentation;
    bool  _shouldPresentOverCurrentContext;
}

@property (nonatomic) bool isCloudSharing;
@property (nonatomic) bool shouldDismissBeforePresentation;
@property (nonatomic) bool shouldPresentOverCurrentContext;

- (id)description;
- (bool)isCloudSharing;
- (void)setIsCloudSharing:(bool)arg1;
- (void)setShouldDismissBeforePresentation:(bool)arg1;
- (void)setShouldPresentOverCurrentContext:(bool)arg1;
- (bool)shouldDismissBeforePresentation;
- (bool)shouldPresentOverCurrentContext;

@end
