/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PegasusConfiguration.framework/PegasusConfiguration
 */

@interface PegasusConfiguration.ConfigFactoryInternal : NSObject <PegasusConfiguration.ConfigFactory>

- (id)init;
- (id)loadWithData:(id)arg1 userAgent:(id)arg2 userDefaults:(id)arg3;
- (id)loadWithUrl:(id)arg1 userAgent:(id)arg2 userDefaults:(id)arg3;

@end
