/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PegasusConfiguration.framework/PegasusConfiguration
 */

@interface PegasusConfiguration.ActivityMonitor : _TtCs12_SwiftObject {
    void delegate;
    void locker;
    void spans;
}

@end
