/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/WirelessDiagnostics
 */

@interface AWDMetricContainer : NSObject {
    PBCodable * _metric;
    unsigned int  _metricId;
}

@property (nonatomic, retain) PBCodable *metric;
@property (nonatomic, readonly) unsigned int metricId;

- (void).cxx_destruct;
- (id)metric;
- (unsigned int)metricId;
- (void)setMetric:(id)arg1;

@end
