/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MediaAnalysis.framework/MediaAnalysis
 */

@interface VCPCNNSmileDetectorEspresso : VCPCNNSmileDetector {
    float * _inputData;
    VCPCNNModelEspresso * _modelEspresso;
}

+ (id)sharedModel:(id)arg1;

- (void).cxx_destruct;
- (int)computeSmileScore:(float*)arg1;
- (void)dealloc;
- (float*)getInputBuffer;
- (id)init;

@end
