/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRIDSClientConnection : MRProtocolClientConnection {
    unsigned int  _discoveryMode;
}

@property (nonatomic) unsigned int discoveryMode;

- (unsigned int)discoveryMode;
- (id)initWithConnection:(id)arg1 queue:(id)arg2;
- (void)setDiscoveryMode:(unsigned int)arg1;

@end
