/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRNowPlayingArtwork : NSObject

@property (nonatomic, readonly) bool hasArtworkData;
@property (nonatomic, readonly) unsigned int type;

- (id)copyImageData;
- (bool)hasArtworkData;
- (unsigned int)type;

@end
