/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRRegisterForGameControllerEventsMessage : MRProtocolMessage

@property (nonatomic, readonly) unsigned int inputMode;

- (id)initWithInputMode:(unsigned int)arg1;
- (unsigned int)inputMode;
- (unsigned long long)type;

@end
