/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRTextInputMessage : MRProtocolMessage

@property (nonatomic, readonly) unsigned long long actionType;
@property (nonatomic, readonly) NSString *text;

- (unsigned long long)actionType;
- (id)initWithActionType:(unsigned long long)arg1 text:(id)arg2;
- (id)text;
- (unsigned long long)type;

@end
