/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/HomeKitBackingStore.framework/HomeKitBackingStore
 */

@interface HMBCloudZonePullResult : HMFObject {
    NAFuture * _processingFuture;
}

@property (readonly) NAFuture *processingFuture;

- (void).cxx_destruct;
- (id)initWithProcessingFuture:(id)arg1;
- (id)processingFuture;

@end
