/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CallHistory.framework/CallHistory
 */

@interface CHLogger : NSObject {
    NSObject<OS_os_log> * _logHandle;
}

@property (nonatomic, readonly) NSObject<OS_os_log> *logHandle;

- (void).cxx_destruct;
- (id)initWithDomain:(const char *)arg1;
- (id)logHandle;

@end
