/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AddressBook.framework/AddressBook
 */

@interface ABSVCardRecord : NSObject {
    void * _record;
}

@property (nonatomic, readonly) void*record;

- (void)dealloc;
- (id)initWithRecord:(void*)arg1;
- (id)initWithVCardRepresentation:(id)arg1;
- (void*)record;

@end
