/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ContextualActionsClient.framework/ContextualActionsClient
 */

@interface CAXContextualActionsSuggestionReceiver : NSObject <CAXContextualActionsXPCInterface, NSXPCListenerDelegate> {
    CAXSuggestionProvider * _suggestionProvider;
    NSXPCListener * _xpcListener;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)dealloc;
- (void)donateSessionSummary:(id)arg1;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)processShortcutsActionSelectionGivenFeedbackEvent:(id)arg1;
- (void)processShortcutsActionSelectionGivenFeedbackEvent:(id)arg1 completion:(id /* block */)arg2;
- (void)processShortcutsSessionGivenSummary:(id)arg1;
- (void)processShortcutsSessionGivenSummary:(id)arg1 completion:(id /* block */)arg2;
- (void)setupXPCListener;
- (void)startWithBlendingLayerServer:(id)arg1;

@end
