/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSSQLObjectFaultRequestContext : NSSQLStoreRequestContext {
    NSFetchRequest * _fetchRequest;
    bool  _forConflictAnalysis;
    NSManagedObjectID * _objectID;
}

- (void)dealloc;
- (bool)executeRequestCore:(id*)arg1;
- (id)initWithObjectID:(id)arg1 context:(id)arg2 sqlCore:(id)arg3;

@end
