/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSSQLManyToMany : NSSQLRelationship {
    NSString * _columnName;
    NSString * _correlationTableName;
    NSString * _orderColumnName;
}

- (id)columnName;
- (id)correlationTableName;
- (void)dealloc;
- (id)initWithEntity:(id)arg1 propertyDescription:(id)arg2;

@end
