/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ShazamCore.framework/ShazamCore
 */

@interface SHAnalytics : NSObject

+ (void)sendEvent:(id)arg1 withPayload:(id)arg2;

@end
