/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ShazamCore.framework/ShazamCore
 */

@interface SHStorefront : NSObject {
    SKCloudServiceController * _cloudServiceController;
}

@property (nonatomic, readonly) SKCloudServiceController *cloudServiceController;

- (void).cxx_destruct;
- (id)cloudServiceController;
- (void)storefrontCountryCode:(id /* block */)arg1;

@end
