/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/HMFoundation.framework/HMFoundation
 */

@interface HMFWiFiManagerDataSource : HMFObject <HMFWiFiManagerDataSource>

@property (getter=isAssertionActive, readonly) bool assertionActive;
@property (readonly) unsigned long long assertionOptions;
@property (getter=isCaptive, nonatomic, readonly) bool captive;
@property (readonly, copy) HMFWifiNetworkAssociation *currentNetworkAssociation;
@property (nonatomic, readonly, copy) NSNumber *currentNetworkRSSI;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <HMFWiFiManagerDataSourceDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (getter=isWoWAsserted, setter=setWoWAsserted:, nonatomic) bool wowAsserted;

+ (id)MACAddressString;

- (void)activateWithOptions:(unsigned long long)arg1;
- (id)currentNetworkAssociation;
- (id)currentNetworkRSSI;
- (void)deactivate;
- (id)delegate;
- (id)initWithWorkQueue:(id)arg1;
- (bool)isAssertionActive;
- (bool)isCaptive;
- (bool)isWoWAsserted;
- (void)performBlockAfterWoWReassertionDelay:(id /* block */)arg1;
- (void)setDelegate:(id)arg1;
- (void)setWoWAsserted:(bool)arg1;

@end
