/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/EventKit.framework/EventKit
 */

@interface EKAlarmUtils : NSObject

+ (void)adjustRelativeAlarmsForEvent:(id)arg1 whenConvertingToIsAllDay:(bool)arg2;
+ (id)adjustedRelativeAlarmOffset:(double)arg1 isAllDay:(bool)arg2;
+ (id)adjustedRelativeAlarmOffsetFromAllDayToTimed:(double)arg1;
+ (id)adjustedRelativeAlarmOffsetFromTimedToAllDay:(double)arg1;

@end
