/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/InstalledContentLibrary.framework/InstalledContentLibrary
 */

@interface MIBundleContainerToken : MIContainerToken {
    NSURL * _bundleURL;
    bool  _hasIdentifiedBundle;
}

@property (nonatomic, readonly) NSURL *bundleURL;
@property (nonatomic, readonly) bool hasIdentifiedBundle;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)bundleURL;
- (void)encodeWithCoder:(id)arg1;
- (bool)hasIdentifiedBundle;
- (id)initWithCoder:(id)arg1;
- (id)initWithContainer:(id)arg1;

@end
