/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/InstalledContentLibrary.framework/InstalledContentLibrary
 */

@interface MIGroupContainer : MIDataContainer

+ (id)groupContainerWithIdentifier:(id)arg1 forPersona:(id)arg2 createIfNeeded:(bool)arg3 error:(id*)arg4;

@end
