/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UserNotificationsKit.framework/UserNotificationsKit
 */

@interface _UNNotificationCommunicationContextService : NSObject

- (id)_updatedCommunicationContext:(id)arg1 bundleIdentifier:(id)arg2;
- (id)init;
- (id)resolveCommunicationContextForRequest:(id)arg1 bundleIdentifier:(id)arg2;

@end
