/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/RunningBoardServices.framework/RunningBoardServices
 */

@interface RBSIdentityAndRecordInfoProvider : NSObject <RBSWrappedLSInfoProvider> {
    NSString * _bundleID;
    NSString * _personaString;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)_providerWithIdentity:(id)arg1 record:(id)arg2;

- (void).cxx_destruct;
- (id)_initWithIdentity:(id)arg1 record:(id)arg2;
- (id)fetchWrappedInfoWithError:(out id*)arg1;

@end
