/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation
 */

@interface CalWidgetUtils : NSObject

+ (void)_refreshWidgetKinds:(id)arg1 reason:(id)arg2;
+ (double)lookaheadIntervalForDaysPerEntry:(long long)arg1;
+ (void)refreshDateWidgets;
+ (void)refreshEventWidgets;

@end
