/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ScreenTimeCore.framework/ScreenTimeCore
 */

@interface STAdminPersistenceController : STPersistenceController

+ (id)sharedController;

- (id)init;
- (id)newBackgroundContext;
- (void)performBackgroundTask:(id /* block */)arg1;
- (void)performBackgroundTaskAndWait:(id /* block */)arg1;
- (bool)saveContext:(id)arg1 error:(id*)arg2;
- (id)viewContext;

@end
