/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/RoomScanCore.framework/RoomScanCore
 */

@interface RSGroupEdge : NSObject <NSCopying> {
    NSUUID * source_object_uuid;
    NSUUID * target_object_uuid;
}

@property (nonatomic, readonly) NSUUID *source_object_uuid;
@property (nonatomic, readonly) NSUUID *target_object_uuid;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)source_object_uuid;
- (id)target_object_uuid;

@end
