/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/RoomScanCore.framework/RoomScanCore
 */

@interface RSNodeInput : NSObject {
    <RSNodeInputProducer> * _producer;
}

@property (nonatomic, readonly) RSNodeConnection *connection;
@property (nonatomic) <RSNodeInputProducer> *producer;

- (void).cxx_destruct;
- (id)producer;
- (void)setProducer:(id)arg1;

// RSNodeInput (null)

+ (id)keyPathsForValuesAffectingConnection;

- (id)connection;

@end
