/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface MTSchemaMTInvocationFailed : SISchemaInstrumentationMessage {
    MTSchemaMTError * _error;
    bool  _hasError;
    bool  _hasQssSessionId;
    SISchemaUUID * _qssSessionId;
}

@property (nonatomic, retain) MTSchemaMTError *error;
@property (nonatomic) bool hasError;
@property (nonatomic) bool hasQssSessionId;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) SISchemaUUID *qssSessionId;

- (void).cxx_destruct;
- (void)deleteError;
- (void)deleteQssSessionId;
- (id)dictionaryRepresentation;
- (id)error;
- (bool)hasError;
- (bool)hasQssSessionId;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (id)qssSessionId;
- (bool)readFrom:(id)arg1;
- (void)setError:(id)arg1;
- (void)setHasError:(bool)arg1;
- (void)setHasQssSessionId:(bool)arg1;
- (void)setQssSessionId:(id)arg1;
- (void)writeTo:(id)arg1;

// MTSchemaMTInvocationFailed (SensitiveConditions)

- (id)applySensitiveConditionsPolicy:(id)arg1;
- (id)suppressMessageUnderConditions;

@end
