/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCGizmoUtilities : NSObject

+ (id)MCFirstPartyCompanionToWatchAppBundleIDs;
+ (void)watchAppBundleIDsForBundleIDs:(id)arg1 completion:(id /* block */)arg2;

@end
