/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCLazyInitializationUtilities : NSObject

+ (void)initAppleIDSSOAuthentication;
+ (void)initAuthKit;
+ (void)initCoreText;
+ (void)initExchangeSyncExpress;
+ (void)initImageIO;
+ (void)initLoggingSupport;
+ (void)initMessage;
+ (void)initSetupAssistant;
+ (void)initSpringBoardServices;
+ (void)initUserManagement;
+ (void)loadBundleAtURL:(id)arg1 completionBlock:(id /* block */)arg2;
+ (void)loadNSBundleAtURL:(id)arg1 completionBlock:(id /* block */)arg2;

@end
