/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _CDKeywordRecord : NSManagedObject

@property (nonatomic) double creationDate;
@property (nonatomic, retain) NSSet *interactions;
@property (nonatomic, retain) NSString *keyword;

@end
