/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/IntentsFoundation.framework/IntentsFoundation
 */

@interface INFSentenceContext : NSObject {
    unsigned long long  _gender;
    NSNumber * _number;
}

@property (nonatomic) unsigned long long gender;
@property (nonatomic, copy) NSNumber *number;

+ (id)sentenceContext;

- (void).cxx_destruct;
- (id)combinedWithContext:(id)arg1;
- (unsigned long long)gender;
- (id)number;
- (void)setGender:(unsigned long long)arg1;
- (void)setNumber:(id)arg1;

@end
