/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@interface TDVectorGlyphRenditionSpec : TDSimpleArtworkRenditionSpec

@property (nonatomic, retain) NSSet *avaliablePointSizes;

- (bool)canBePackedWithDocument:(id)arg1;
- (id)createCSIRepresentationWithCompression:(bool)arg1 colorSpaceID:(unsigned long long)arg2 document:(id)arg3;

// TDVectorGlyphRenditionSpec (CoreDataProperties)

+ (id)fetchRequest;

@end
