/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SALocalSearchVehicleEventDelete : SADomainCommand

@property (nonatomic, copy) NSArray *eventIds;

+ (id)vehicleEventDelete;
+ (id)vehicleEventDeleteWithDictionary:(id)arg1 context:(id)arg2;

- (id)encodedClassName;
- (id)eventIds;
- (id)groupIdentifier;
- (bool)requiresResponse;
- (void)setEventIds:(id)arg1;

@end
