/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SAMovieV2TheaterListSnippet : SAUISnippet

@property (nonatomic, copy) NSArray *theaterListCells;

+ (id)theaterListSnippet;
+ (id)theaterListSnippetWithDictionary:(id)arg1 context:(id)arg2;

- (id)encodedClassName;
- (id)groupIdentifier;
- (void)setTheaterListCells:(id)arg1;
- (id)theaterListCells;

@end
