/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TeaFoundation.framework/TeaFoundation
 */

@interface _TtC13TeaFoundationP33_3E775B95AA8F4C6167C1B13E33C411A69Localized : _TtCs12_SwiftObject

@end
