/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TeaFoundation.framework/TeaFoundation
 */

@interface TeaFoundation.BackgroundNetworkSession : _TtCs12_SwiftObject {
    void session;
    void urlSessionDelegate;
}

@end
