/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLCloudMasterMediaMetadata : PLManagedObject

@property (nonatomic, retain) PLAdditionalAssetAttributes *additionalAssetAttributes;
@property (nonatomic, retain) PLCloudMaster *cloudMaster;
@property (nonatomic, retain) NSData *data;

+ (id)entityName;

// PLCloudMasterMediaMetadata (PLJournalEntryPayload)

- (void)_addPayloadIfValidForAsset:(id)arg1 changedKeys:(id)arg2 toPayloads:(id)arg3 modelProperties:(id)arg4;
- (id)payloadID;
- (id)payloadsForChangedKeys:(id)arg1;

@end
