/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLFetchRecorderPredicateVisitor : NSObject <NSPredicateVisitor> {
    bool  _foundOperatorIN;
}

@property (nonatomic, readonly) bool foundOperatorIN;

- (void)examinePredicate:(id)arg1;
- (bool)foundOperatorIN;
- (void)reset;
- (void)visitPredicate:(id)arg1;
- (void)visitPredicateExpression:(id)arg1;
- (void)visitPredicateOperator:(id)arg1;

@end
