/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MetricsKit.framework/MetricsKit
 */

@interface MTPerfEventHandlers : MTEventHandlers {
    MTFlexiblePerfEventHandler * _flexible;
}

@property (nonatomic, readonly) MTFlexiblePerfEventHandler *flexible;
@property (nonatomic, readonly) MTLoadUrlEventHandler *loadUrl;
@property (nonatomic, readonly) MTPageRenderEventHandler *pageRender;

- (void).cxx_destruct;
- (Class)baseDataProviderClass;
- (id)flexible;
- (id)loadUrl;
- (id)pageRender;
- (void)registerDefaultEventHandlers;

@end
