/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface _CNDistinctObservable : CNObservable {
    <CNObservable> * _observable;
    NSMutableSet * _previouslyObservedResults;
}

- (void).cxx_destruct;
- (bool)_resultIsDistinct:(id)arg1;
- (id)initWithObservable:(id)arg1;
- (id)subscribe:(id)arg1;

@end
