/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface _CNLazyArrayOperatorDistinct : _CNLazyArrayOperator {
    NSMutableSet * _seenValues;
}

- (void).cxx_destruct;
- (id)initWithInput:(id)arg1;
- (id)nextObject;

@end
