/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
 */

@interface CNSimulatedCrashReporter : NSObject

+ (id)os_log;
+ (void)simulateCrashWithCode:(long long)arg1 description:(id)arg2;
+ (void)simulateCrashWithMessage:(id)arg1;

@end
