/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPlaceExternalActionLink : NSObject {
    GEOPDLink * _actionLink;
    NSMapTable * _attributionMap;
}

@property (nonatomic, readonly) GEOPlaceExternalActionLinkAppClipParams *appClipParams;
@property (nonatomic, readonly) GEOQuickLink *appClipRepresentedAsQuickLink;
@property (nonatomic, readonly) GEOAttributionApp *attributionAppForMapsExtension;
@property (nonatomic, readonly) GEOQuickLink *quickLink;
@property (nonatomic, readonly) GEOPlaceExternalActionLinkQuickLinkParams *quickLinkParams;
@property (nonatomic, readonly) GEOPlaceExternalActionLinkExtensionParams *siriExtensionParams;
@property (nonatomic, readonly) int type;

- (void).cxx_destruct;
- (id)appClipParams;
- (id)initWithLinkData:(id)arg1 attributionMap:(id)arg2;
- (id)quickLinkParams;
- (id)siriExtensionParams;
- (int)type;

// GEOPlaceExternalActionLink (ConversionHelpers)

- (id)appClipRepresentedAsQuickLink;
- (id)appClipUsingArtworkURL:(id)arg1 title:(id)arg2;
- (id)attributionAppForMapsExtension;
- (id)quickLink;

@end
