/* Generated by RuntimeBrowser
   Image: /Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/APConfigurationSystem.framework/APConfigurationSystem
 */

@interface APECSettingsConfig : APConfiguration

@property (nonatomic, retain) NSNumber *batchSize;
@property (nonatomic, retain) NSNumber *periodicDelay;
@property (nonatomic, retain) NSString *serverEnvironment;
@property (nonatomic, retain) NSDictionary *serverSettings;

// APECSettingsConfig (null)

+ (id)path;

@end
